### ISSUE TITLE
PropertyFieldListPicker onGetErrorMessage not disabling Apply Button

### ISSUE THREAD

**Issue by robpearmain** [pnp/sp-dev-fx-property-controls#134]
#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [    1.13.1    ]

#### Expected / Desired Behavior / Question

Property Pane apply disabled and message displayed if no list selected

#### Observed Behavior

Error message does not appear until you select a blank item (e.g. select list then select blank) and does not effect apply button

#### Steps to Reproduce

wire up onGetErrorMessage

**Comment by AJIXuMuK** [comment]
SPFx still doesn't allow to disable Apply button based on some criteria.
If you still need such a functionality I would create an issue in [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) or even a new [user voice](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform) entry.
