### ISSUE TITLE
Consider exporting PlaceholderWithCallout 

### ISSUE THREAD

**Issue by hugoabernier** [pnp/sp-dev-fx-property-controls#146]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 1.13.1 ]

#### Expected / Desired Behavior / Question

The property controls with callouts are all great. However, I often find myself looking for a PnP property control that doesn't have callouts, or find myself wishing that the standard SPFx property controls had them. 

For example, the Spin Button doesn't have a callout.

Although I could write my own callout versions of the controls I need, I found that the majority of callout PnP controls consist of a `PlaceholderWithCallout` wrapped around a property control. For example, the checkbox with callout consists of:

```TypeScript
 <PlaceholderWithCallout {...this.props}>
<Checkbox {...this.props} label={this.props.text} />
</PlaceholderWithCallout>
```

Thinking it would be easy to simply use the `PlaceholderWithCallout` with whatever property control I needed to have callouts, I soon realized that the `PlaceholderWithCallout` is not exported and therefore cannot be used outside of the PnP library.

My suggestion consists of two possible solutions:
* Export `PlaceholderWithCallout` to allow users to write their own custom property controls without having to duplicate the `PlaceholderWithCallout` code (least effort for PnP library contributors, but bigger learning curve for consumers of the PnP property controls); or
* Create a new PnP property control which implements the `IPropertyPaneField` interface and consists of an externally-available `PlaceholderWithCallout`. It wraps around property controls to provide callout functionality without having to create a custom property control. This would require more effort to implement (for the PnP library contributors), but would make it easier for consumers of the PnP library to use.

I'd be happy to implement this functionality and submit PR, if needed.

**Comment by AJIXuMuK** [comment]
Hi @hugoabernier!
I think it's a good idea and if you already have a plan in your head I think PR from you would be the best thing to have :)

**Comment by hugoabernier** [comment]
Happy to oblige. Will submit a PR as soon as I can.

**Comment by AJIXuMuK** [comment]
Seems like `PlaceholderWithCallout` is exported from the library.

Closing this one as I haven't heard any need of more complex option 2.
