### ISSUE TITLE
[PropertyFieldNumber] Improper handling of falsey minValue or maxValue of 0

### ISSUE THREAD

**Issue by TheTedAdams** [pnp/sp-dev-fx-property-controls#150]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.14.0]

#### Expected / Desired Behavior / Question
Expected that if `minValue` is set to `0`, negative numbers will not be allowed.

#### Observed Behavior
When minValue is set to 0, negative numbers are allowed.

#### Steps to Reproduce
Add the control with `minValue: 0`, and input any negative number. Observe there are no validation errors.

#### Suggested Resolution
This is a simple case of using truthiness/falseyness to determine the existence of a property, when one of the valid values of the property, `0`, is falsey.

[Relevant Code:](https://github.com/SharePoint/sp-dev-fx-property-controls/blob/master/src/propertyFields/number/PropertyFieldNumberHost.tsx#L38-L44)
```js
if (this.props.minValue && nrValue < this.props.minValue) {
  return `${strings.MinimumNumberValidationMessage} ${this.props.minValue}`;
}
// Check if the number is greater than the maximum value
if (this.props.maxValue && nrValue > this.props.maxValue) {
  return `${strings.MaximumNumberValidationMessage} ${this.props.maxValue}`;
}
```

Should be:
```js
if (this.props.minValue != null && nrValue < this.props.minValue) {
  return `${strings.MinimumNumberValidationMessage} ${this.props.minValue}`;
}
// Check if the number is greater than the maximum value
if (this.props.maxValue != null && nrValue > this.props.maxValue) {
  return `${strings.MaximumNumberValidationMessage} ${this.props.maxValue}`;
}
```

This should also be fixed [here](https://github.com/SharePoint/sp-dev-fx-property-controls/blob/master/src/propertyFields/number/PropertyFieldNumberHost.tsx#L64-L66) in the `_onChanged()` method:

```js
if (!isNaN(Number(value))) {
  const nrValue = parseInt(value);
  if ((!this.props.minValue || nrValue >= this.props.minValue) && (!this.props.maxValue || nrValue <= this.props.maxValue)) {
    // Trigger change for the web part
    this.props.onChanged(nrValue);
  }
}
```

I can do the PR if wanted, just figured with how long it would take to set up the local project maybe someone else could do the simple fix.

**Comment by AJIXuMuK** [comment]
Thanks @TheTedAdams for reporting the issue and sorry for a long response.

This has been finally fixed and will be available in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/)
