### ISSUE TITLE
[PropertyFieldNumber] Decimal / Float values are rounded to ints

### ISSUE THREAD

**Issue by TheTedAdams** [pnp/sp-dev-fx-property-controls#151]
#### Category
- [x] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.14.0]

#### Expected / Desired Behavior / Question
Expected that when inputting a decimal value, the decimal number would be passed to my web part properties.

#### Observed Behavior
Decimals are parsed to ints.

#### Additional Comments
I realize that this is a PropertyFieldNumber component and perhaps the team does not intend it to support floats or decimals, however in that case I would expect a validation error rather than for the inputted value to be silently changed.

This could be an option on the number component that sets it to allow floats. This could be an ask for a new control PropertyFieldFloat or PropertyFieldDecimal, or the control could just use `Number()` to parse values like it does when checking for `NaN` instead of using `parseInt()`.

I think at the least though, if the answer is that it is not the intent for this control to support non integer numeric values, then it should throw a validation error when supplied with a decimal rather than silently converting it to an int, as that is not an obvious behavior.

**Comment by AJIXuMuK** [comment]
Hi @TheTedAdams,

We've added a new property `precision` to the `PropertyFieldNumber`. Now the value is rounded based on the property.
If it's not set you'll get the value as is.

The change will be available in the next release.
In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/)
