### ISSUE TITLE
CustomCollectionFieldType.dropdown doesn't open on focus

### ISSUE THREAD

**Issue by malcom1120** [pnp/sp-dev-fx-property-controls#158]
#### Category
- [X] Enhancement
- [X] Bug
- [ ] Question

#### Version

 1.14.0

#### Expected / Desired Behavior / Question

When tabbing across a row, the dropdown field type should open automatically to indicate it is a dropdown option.

#### Observed Behavior

When tabbing across a row, the dropdown field type doesn't open the list options automatically.

#### Steps to Reproduce

Create a collection data with two columns of text field and add a dropdown with a few options. Then try to enter data and use tab to move to next column to enter data. The dropdown field column will just focus, but not open the dropdown options until clicked. Using the up/down arrows does however toggle through the options, but it never opens.

**Comment by AJIXuMuK** [comment]
Hi @malcom1120,

Standard behaviors for focused dropdowns is just show the focus.
key down is usually used to either open the list of options or iterate through the options.

We're using the behavior of [Fluent UI Dropdown](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown)
