### ISSUE TITLE
CustomCollectionFieldType.fabricIcon - Consider typeahead for icon name

### ISSUE THREAD

**Issue by malcom1120** [pnp/sp-dev-fx-property-controls#160]
#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

1.14.0

#### Desired Behavior

To make the icon field type easier to use for the simple consumer, it would be nice to have a type ahead feature for the user when they start typing for the name.  I have found that even as a developer, it have to go to the icon lookup page a lot to get the correct name.

**Comment by estruyf** [comment]
@malcom1120 thank you for your idea. Initially this was the case that we worked with a predefined list. The issue with it, is that it changes so often, that it could be that you can use or can’t use a specific icon. The icon font is already loaded by SharePoint itself, this is something we do not own. Which makes it even harder to guess which icons would be available. 

An option would be, that we introduce the initial list again, wouldn’t limit the user by the list. It can be used as a suggestion, but the user found another icon which is not in the list, he will still be able to use it. Would that be ok for you?

**Comment by malcom1120** [comment]
I think that is a great start as it really needs a type ahead to make it user friendly outside developers, but in my other coding I found that all the registered Icons are in the SP global settings variable.  Do you think you could make it query that array? I think there is a way to get it from the Fabric React package as well. I definitely like the idea of not limiting it to the look ahead values.

window.__globalSettings__.icons

**Comment by malcom1120** [comment]
I was looking through the Office UI React package and it looks like there is a IconNames enum in the @uifabric/icons package.

**Comment by AJIXuMuK** [comment]
@malcom1120 - it's been a while :)
We've made the changes that will be available in the next release.
You'll be able to use `IconPicker` instead of `TextBox` in the icon field. See related PR for details.

**Comment by AJIXuMuK** [comment]
Included in v3.4.0
