### ISSUE TITLE
Markdown property pane control?

### ISSUE THREAD

**Issue by hugoabernier** [pnp/sp-dev-fx-property-controls#162]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Expected / Desired Behavior / Question

I recently needed a way to add help in a web part property pane that shows users the syntax they should use -- similar to what the out-of-the-box Markdown web part does.

Here is the out-of-the-box Markdown web part's property pane:
![Markdown within Markdown](https://github.com/hugoabernier/react-diagram-webparts/raw/master/assets/OOBMarkdown.png)

And here is mine (see the **Syntax help** group in the property pane below):
![Markdown property control](https://github.com/hugoabernier/react-diagram-webparts/raw/master/assets/MarkdownPropertyControl.gif)

Is this something that the community would need? I see it as a complement to the WebPartInformation control (which is awesome!), but it adds support for any markdown, and allows the web part hosting the control to override how some of the tags will render. 

In my sample, I render the H2 and H3 tags to mimic the look and feel of the Markdown web part.

I want to make it clear: this is a **read-only** view of markdown content, used to provide help and guidance, not a markdown editor. 

If you want to see more, here is the [repo](https://github.com/hugoabernier/react-diagram-webparts).

Let me know your thoughts?

**Comment by AJIXuMuK** [comment]
Hey @hugoabernier,

It can be something helpful!
