### ISSUE TITLE
[PropertyFieldCodeEditor] code beautify

### ISSUE THREAD

**Issue by ssvinciak** [pnp/sp-dev-fx-property-controls#165]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.14.1]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Is there any way how to bind shortcut to format(beautify) code when using Code Editor? I have used PropertyFieldCodeEditor for JSON and it would be awesome if the edited file could be formatted. 

Thanks!

**Comment by nanddeepn** [comment]
Hi, I can work on this.

**Comment by AJIXuMuK** [comment]
Thanks @nanddeepn - it would be great!

**Comment by AJIXuMuK** [comment]
The PR has been merged and will be available in the next release.

**Comment by AJIXuMuK** [comment]
The version has been released.
