### ISSUE TITLE
Clear button on People Picker

### ISSUE THREAD

**Issue by PooLP** [pnp/sp-dev-fx-property-controls#169]
#### Category
- [x] Enhancement
- [ ] Bug
- [x] Question

#### Desired Behavior / Question

Hi,
Would it be a good idea to add a Clear button to reset the field?

Thanks

**Comment by AJIXuMuK** [comment]
Hi @PooLP!
It's a good idea to have clear button. But under the hood we're using a picker from Fluent UI (Office UI Fabric). And that picker doesn't have an option to show clear button.
Although the feature is nice to have, I wouldn't go with customization just for it.

**Comment by PooLP** [comment]
Hi,
ok, couldn't it have this button on the Fluent UI select component? it would also be useful in multi.

**Comment by AJIXuMuK** [comment]
Neither pickers nor dropdowns have the ability to display clear button.
