### ISSUE TITLE
PropertyFieldPeoplePicker is slow

### ISSUE THREAD

**Issue by TarekA** [pnp/sp-dev-fx-property-controls#175]
#### Category
- [ x ] Enhancement
- [ ] Bug
- [ x ] Question

#### Version

Please specify what version of the library you are using: [1.14.1 ]

#### Expected / Desired Behavior / Question
When I type something into PeoplePicker for the first time, it takes 20 to 30 seconds for me to get a suggestion. The next attempts will be faster (~ 1 second). 

1. Is there a way that this can be done faster? 

2. and does the waiting time increase with the number of users?

**Comment by AJIXuMuK** [comment]
Hi @TarekA,

Sorry for not responding back.

Is it still an issue? I've never seen such a problem with people picker.

If it's still the case, could you provide some info regarding your environment? how many users do you have? How the OOB people picker speed is (for example, if you're trying to edit User or Group field value in modern UI)?

Thanks!
