### ISSUE TITLE
Can’t connect securely to this page

### ISSUE THREAD

**Issue by MichelLaplane** [pnp/sp-dev-fx-property-controls#185]
Category : Question
Version : current
I have just downloaded the repository to test all the property controls.
I have installed all the dependencies using "npm install"
When trying to launch the test component using "gulp serve" my edge browser (using chrome has the same behavior) is launching and I get this error :
"Can’t connect securely to this page
This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.
Try this:
Go back to the last page"
Any suggestions?
Many thanks

**Comment by MichelLaplane** [comment]
Category : Question
Version : current

I have just downloaded the repository to test all the property controls.
I have installed all the dependencies using "npm install"
When trying to launch the test component using "gulp serve" my edge browser (using chrome has the same behavior) is launching and I get this error : 
"Can’t connect securely to this page
This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.
Try this:
Go back to the last page"
Any suggestions?
Many thanks

**Comment by estruyf** [comment]
This has probably to do with the node version you are using. This project is still using version `1.3.0` of SPFx, which only supported node version `6`. When you are using version `8` or higher, you could run into the HTTP2 issue.

Best is to test out the project with node version 6, if you want to do it with version 8, check out this issue: https://github.com/SharePoint/sp-dev-docs/issues/1002

**Comment by AJIXuMuK** [comment]
@MichelLaplane - has it been resolved for you using NodeJS v6 or v8?

**Comment by MichelLaplane** [comment]
I've update to last SPFx framework version making different modifications and it works quite well. Thank you for your inquiry.
