### ISSUE TITLE
Add ability to hide Date and show only Time field in PropertyFieldDateTimePicker

### ISSUE THREAD

**Issue by hasannaqvi83** [pnp/sp-dev-fx-property-controls#195]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version: [1.16.0]
It would be great if we can have Time only field for PropertyFieldDateTimePicker control and add Time enum in DateConvention.

Cheers,
Hasan.

**Comment by nanddeepn** [comment]
Hi @AJIXuMuK 
I can take this up!

**Comment by nanddeepn** [comment]
Hi @AJIXuMuK,
I have submitted PR https://github.com/SharePoint/sp-dev-fx-property-controls/pull/244 for this. Please review and let me know for any changes needed.
Thank you!

**Comment by AJIXuMuK** [comment]
Hi @hasannaqvi83!
This has been implemented (thanks @nanddeepn) and will be available in the next release.
In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)
