### ISSUE TITLE
PropertyFieldPeoplePicker does not disable the users

### ISSUE THREAD

**Issue by Dangerous-Mind** [pnp/sp-dev-fx-property-controls#202]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ v1.16  ]

#### Expected / Desired Behavior / Question
Peoplepicket should all be disabled when the disabled option is true

#### Observed Behavior
Only the field is disabled. The users that are already inside the field are not disabled and people can remove them.

#### Steps to Reproduce
Create a PropertyFieldPeoplePicker. 
Add a user.
Disable the PropertyFieldPeoplePicker.

**Comment by AJIXuMuK** [comment]
Hi @Dangerous-Mind 
This is an issue of underlying Office UI Fabric picker in the version we're using (5.131.0).
There are plans to update to a newer version of OUIFR. When it's done the issue will be fixed.

**Comment by AJIXuMuK** [comment]
Hi @Dangerous-Mind - this should be fixed in the version 2.0.0
