### ISSUE TITLE
commonJS module configuration prevents externalizing package

### ISSUE THREAD

**Issue by baywet** [pnp/sp-dev-fx-property-controls#205]
Reflecting https://github.com/SharePoint/sp-dev-fx-controls-react/issues/415

https://github.com/SharePoint/sp-dev-fx-property-controls/blob/361a5e4c89e143388302555b71ffac82ff432a9e/tsconfig.json#L5

**Comment by AJIXuMuK** [comment]
Moved to `esnext` module configuration
