### ISSUE TITLE
[PropertyFieldPeoplePicker] targetProperty is not updated properly when using nested/complex attributes

### ISSUE THREAD

**Issue by doxic012** [pnp/sp-dev-fx-property-controls#221]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.16.0]

#### Expected / Desired Behavior / Question
With the default PropertyPane-Controls like Text or Input, you can specify nested targetProperties like 'myElement.targetPropertyName' which modifies the value of the sub-property 'targetPropertyName'.

e.g. if I have an object using the following properties and my WebPart-property interface is the following:
```typescript
export interface MyElement { 
    text: string; 
    anotherText: string; 
    person: IPropertyFieldGroupOrPerson
}
export interface ICustomWebPartProps {
    element: MyElement;
    elementArray: MyElement[];
}
```

Then the PropertyPaneText-Controls modifies the 'name'-Property inside this.properties directly (works with array indices as well):
```typescript
PropertyPaneTextField('element.text', {
    label: 'insert text',
    value: element.text
})
PropertyPaneTextField('elementArray[1].anotherText', {
    label: 'insert another text',
    value: elementArray[1].anotherText
})
```

The resulting properties of the WebPart after changing the values of the Textfields would be (this.properties of the WebPart):
```typescript
{
    element: {text: 'xyz', anotherText: '', person: null},
    elementArray[{text: '', anotherText: 'xyz', person: null}]
}
```
Using the PropertyFieldPeoplePicker I would expect the same behaviour like this:
```typescript
PropertyFieldPeoplePicker('element.person', {
    key: 'peoplePicker_id',
    label: 'Select a person',
    multiSelect: false,
    context: this.context,
    principalType: [PrincipalType.Users],
    properties: this.properties,
    onPropertyChange: this.onPropertyPaneFieldChanged
})
```
After entering a person (this.properties of the WebPart):
```typescript
{
   element: {text: 'xyz', anotherText: '', person: {login: '...', fullName: '...', ...}}
}
```

#### Observed Behavior
The observed behaviour of the PropertyFieldPeoplePicker is that it modifies the 'nested' property 'element.name' on the webpart properties itself.

So the result is the following after changing a person (this.properties of the WebPart):
```typescript
{
    element: {text: 'xyz', anotherText: '', person: null},
    element.person: {login: '...', fullName: '...', ...}
}
```

#### Steps to Reproduce
Use a property with one or more attributes inside the WebPartProps and try to modify the properties attributes directly by choosing the value for `targetProperty` with a dot
(e.g. PropertyFieldPeoplePicker('element.person', { ... }))

The default way of SharePoint updating properties using Custom PropertyPane-Fields is done by implementing the IPropertyPaneCustomFieldProps interface and using the onChangeCallback-Method inside onRender (e.g. using React):

```typescript
From @microsoft/sp-property-pane (1.9.1):
export declare interface IPropertyPaneCustomFieldProps {
    /**
     * This API will be called once the custom field is mounted on the host element.
     *
     * @param domElement - DOM element on which the custom control needs to be mounted.
     * @param context - Instance specific context. This context was passed in the constructor.
     * @param changeCallback - Callback called when a field changes within the custom field.
     *  This will allow the property pane to be aware of the change and act accordingly.
     *  @param targetProperty - associated target property from the properties bag.
     *    if not provided then a custom value which is unique at the custom field level is assigned,
     *    which will be in the form of `__CustomField_<key provided when the custom field is created>`.
     *  @param newValue - new value of the property.
     *    newValue is ignored if targetProperty is not specified.
     */
    onRender: (domElement: HTMLElement, context?: any, changeCallback?: (targetProperty?: string, newValue?: any) => void) => void;

...
```

A simple implementation would be using this onChangeCallback-method:
```typescript
public onRender(elem: HTMLElement, context: any, onChangeCallback: (targetProperty?: string, newValue?: any) => void): void {
  const input: React.ReactElement<CustomInputProps> = React.createElement(CustomInput, {
    // Here happens the magic, as we call the passed onChangeCallback-Method that triggers the re-render process and updates the property      
    onValueChange: (newValue) => onChangeCallback(this.targetProperty, newValue)
  });
  ReactDOM.render(input, elem);
}

```

The interface of the implementation from IPropertyFieldPeoplePicker indicates that this callback-method is not used:

```typescript
IPropertyFieldPeoplePicker.d.ts:

/**
 * Private properties of the PropertyFieldPeoplePicker custom field.
 * We separate public & private properties to include onRender & onDispose method waited
 * by the PropertyFieldCustom, witout asking to the developer to add it when he's using
 * the PropertyFieldPeoplePicker.
 *
 */
export interface IPropertyFieldPeoplePickerPropsInternal extends IPropertyFieldPeoplePickerProps {
    targetProperty: string;
    onRender(elem: HTMLElement): void;
    onDispose(elem: HTMLElement): void;
}
```

**Comment by AJIXuMuK** [comment]
Thanks @doxic012 for reporting that!

> The interface of the implementation from IPropertyFieldPeoplePicker indicates that this callback-method is not used

That is not completely true. We're using internal `onRender` method to re-render the component.

Regarding the issue itself - it looks like it is really unsupported and we need to look into fixing that for the controls.

**Comment by doxic012** [comment]
> > The interface of the implementation from IPropertyFieldPeoplePicker indicates that this callback-method is not used
> 
> That is not completely true. We're using internal `onRender` method to re-render the component.
Yes, sorry for that! I looked into the code here and saw it afterwards.

> Regarding the issue itself - it looks like it is really unsupported and we need to look into fixing that for the controls.

Did some more testing on this and found kind of a workaround. I tested four different types of PeoplePicker-Fields, two times using `this properties` as passed argument for "properties" and the other two times I passed this.properties.element (The first one is complete, I omitted the additional properties here for more readability):

```typescript
PropertyFieldPeoplePicker('person', {
  key: 'peoplepicker_props',
  label: 'person on this.properties',
  multiSelect: false,
  context: this.context,
  principalType: [PrincipalType.Users],
  initialData: element.person ? [element.person] : [],
  properties: this.properties,
  onPropertyChange: (targetProp, oldValue, newValue) => this.onPropertyPaneFieldChanged(targetProp, oldValue, newValue)
}),
PropertyFieldPeoplePicker('element.person', {
  key: 'peoplepicker_props_2',
  label: 'element.person on this.properties',
  properties: this.properties
}),
PropertyFieldPeoplePicker('person', {
  key: 'peoplepicker_props.element',
  label: 'person on this.properties.element',
  properties: this.properties.element
}),
PropertyFieldPeoplePicker('element.person', {
  key: 'peoplepicker_props.element_2',
  label: 'element.person on this.properties.element',
  properties: this.properties.element
})
```

The results are the following from console.log in order (using this.properties in the triggered onRender-method), each with a clean webpart without modified properties:

1.
 ```
onPropertyPaneFieldChanged person [] [{…}]
onPropertyPaneFieldChanged person [{…}] [{…}]
onRender {element:{person: null}, person: [{...}]}
```
2.
```
onPropertyPaneFieldChanged person [] [{…}]
onPropertyPaneFieldChanged person [{…}] [{…}]
onRender {element:{person: null}, 'element.person': [{…}]}
```
3.
```
onPropertyPaneFieldChanged element.person [] [{…}]
onPropertyPaneFieldChanged element.person [{…}] [{…}]
onRender {element:{person: [{…}]}, 'element.person': [{…}]} <-- Same person in both properties
```
4.
```
onPropertyPaneFieldChanged element.person [] [{…}]
onPropertyPaneFieldChanged element.person undefined [{…}]
onRender {element:{'element.person': [{...}]}}
```

I guess I can live with the third option applying the new value for "person" to both this.properties as well as this.properties.element.

**Comment by AJIXuMuK** [comment]
Finally, it has been fixed.
Not only for People Picker, but for other controls as well.

The fix will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by AJIXuMuK** [comment]
`v2.4.0` has been released.
