### ISSUE TITLE
new property pane control  - Azure function picker

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-property-controls#224]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

Hey, I am thinking this would be useful.  Would anyone else be interested?

**Comment by joelfmrodrigues** [comment]
@russgove what type of usage did you envisage here? Perhaps save the function Url for a future request?

**Comment by russgove** [comment]
Sorry for delayed response. I don’t remember the original issue , so i must have found a workaround!
I thing the gist is that if i had a web part that’s going to call an azure function, but there were several different versions of that function , i would be able to choose the one i wanted.

closing ticket, as it doesn’t seem to make sense now.
