### ISSUE TITLE
PropertyFieldSitePicker: Doesn't work at root site

### ISSUE THREAD

**Issue by juanmad1** [pnp/sp-dev-fx-property-controls#231]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 1.17.0 ]

#### Expected / Desired Behavior / Question

**When I search in the field positioned at any site collection:**

https://_tenant_.sharepoint.com/sites/prueba2/_layouts/15/workbench.aspx
![image](https://user-images.githubusercontent.com/33957888/77743138-e6629300-7017-11ea-8a44-7f6829550802.png)

**Make the following request:**

![image](https://user-images.githubusercontent.com/33957888/77743545-8ae4d500-7018-11ea-9cff-eb834ac6da0b.png)

#### Observed Behavior

**When I search the field positioned at the root site collection:**

https://_tenant_.sharepoint.com/_layouts/15/workbench.aspx
![image](https://user-images.githubusercontent.com/33957888/77743685-bc5da080-7018-11ea-87f4-ea94033f38ad.png)

**Make the following request:**

![image](https://user-images.githubusercontent.com/33957888/77744106-63dad300-7019-11ea-95a4-fec8649bb14a.png)

#### Steps to Reproduce

Run a webpart in the workbench and search for a site in the PropertyFieldSitePicker from different site collections

**Comment by AJIXuMuK** [comment]
The issue has been fixed.
You can test it in beta version and it'll be included in the next release.
