### ISSUE TITLE
Broken link in PropertyFieldDateTimePicker docs

### ISSUE THREAD

**Issue by RamPrasadMeenavalli** [pnp/sp-dev-fx-property-controls#242]
#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Observed Behavior
The link for OnGetErrorMessage documentation is broken in this page

https://github.com/SharePoint/sp-dev-fx-property-controls/blob/master/docs/documentation/docs/controls/PropertyFieldDateTimePicker.md

**Comment by RamPrasadMeenavalli** [comment]
Looks like this is the correct url - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/validate-web-part-property-values

Submitted a PR

**Comment by AJIXuMuK** [comment]
The PR has been merged and will be available in the next release.

**Comment by AJIXuMuK** [comment]
The version has been released.
