### ISSUE TITLE
Discussion for New Enhancement on MessageBar Control

### ISSUE THREAD

**Issue by kunj-sangani** [pnp/sp-dev-fx-property-controls#247]
#### Category
- [x] Enhancement

#### Question
I am working on a new Enhancement which would allow users to add [MessageBar from Fluent UI](https://developer.microsoft.com/en-us/fluentui#/controls/web/messagebar) in property pane control 
My question is should we allow actions
Would this enhancement of having MessageBar be helpful ? (some use case :- Displaying success message or error message or warning when working with property controls)
Would it be helpful to the users ?

**Comment by AJIXuMuK** [comment]
Hi @kunj-sangani!
Thank you for bringing this up.

@joaojmendes has implemented `Message` component in #248 
Is it the same as you planned to add?
