### ISSUE TITLE
ComboBoxListItemPicker fetching only 100 items~! It should fetch all items from a list?

### ISSUE THREAD

**Issue by ashishasolkar** [pnp/sp-dev-fx-property-controls#249]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version
**"@pnp/spfx-controls-react": "1.18.0"**
"@microsoft/sp-core-library": "1.10.0",
"@microsoft/sp-lodash-subset": "1.10.0",
"@microsoft/sp-office-ui-fabric-core": "1.10.0",
"@microsoft/sp-property-pane": "1.10.0",
"@microsoft/sp-webpart-base": "1.10.0",
"@pnp/sp": "^2.0.4",

#### Expected / Desired Behavior / Question
Currently ComboBoxListItemPicker control can fetch first 100 items from list. Expected behavior is to   fetch all the items from list for specified column.

#### Observed Behavior
ComboBoxListItemPicker can fetch only first 100 items.

#### Steps to Reproduce
1. Create react based spfx webpart.
2. Add ComboBoxListItemPicker control as described in article:
https://pnp.github.io/sp-dev-fx-controls-react/controls/ComboBoxListItemPicker/

`<ComboBoxListItemPicker listId='da8daf15-d84f-4ab1-9800-7568f82fed3f'
                        columnInternalName='Title'
                        keyColumnInternalName='Id'
                        filter="Title eq 'SPFx'"
                        onSelectedItem={this.onSelectedItem}
                        webUrl={this.context.pageContext.web.absoluteUrl}
                        spHttpClient={this.context.spHttpClient} />`

For next steps make sure you are at-least having office 365 dev subscription.
3. Create a custom/generic list - Countries.
4. Enter in "Quick Edit" mode of list and enter values from below mentioned link in "Title" column:
https://alphabetizer.flap.tv/lists/list-of-all-world-countries.php
5. Map Countries list and Title column with ComboBoxListItemPicker.
6. Run the project. It will fetch only first 100 items from list and not all the items.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @ashishasolkar!
This issue is related to [Reusable Controls](https://github.com/pnp/sp-dev-fx-controls-react/) repo, not Property Controls.
Could you please create the same issue in the correct repo?

**Comment by ashishasolkar** [comment]
Sure Thanks. You may close this case. I will create new case in another repo.
