### ISSUE TITLE
PermissionLevel/RoleDefinition selector

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-property-controls#25]
#### Category
[ x] Enhancement

[ ] Bug

[ ] Question

#### Version

We could use a PermissionLevel selector to let an admin select a PermissionLevel/RoleDefinition.

**Comment by estruyf** [comment]
Would you see this as a separate control?

**Comment by russgove** [comment]
only retrieve the permission levels add let user select. right now I make them type t in. I can create it if I find some free time

**Comment by russgove** [comment]
Literally just a dropdown that has read, contribute, and whatever other levels are configured on the site/

**Comment by sharepointknight** [comment]
Looks like this has already been implemented as part of a previous pull request. #268

**Comment by AJIXuMuK** [comment]
@russgove - could you please check if the implemented control fits your needs?
