### ISSUE TITLE
Dynamic options in PropertyFieldCollectionData

### ISSUE THREAD

**Issue by lafe** [pnp/sp-dev-fx-property-controls#260]
#### Category
- [X] Enhancement
- [ ] Bug
- [X] Question

#### Version

Please specify what version of the library you are using: 1.18

#### Question

We have to implement a somewhat complex configuration panel, that also has some "Cascading Dropdowns" (i.e. dropdowns that depend on each other; e.g. selection of country lists all available cities). The `PropertyFieldCollectionData` is an almost perfect match for this requirement. However, as far as I can tell, the available options of the dropdowns are currently static and cannot be changed dynamically during runtime, so that dynamic updates of dropdowns based on the value of other values is currently not possible. Is this correct or have I overlooked something?

If this feature is currently not implemented, would a PR be welcomed that implements such a behavior or is it out of scope of this project?

**Comment by SoHoOps** [comment]
I'm currently working on a complex usage as well, trying to cascade the drop downs based on the first drop down. I have also not found a way to implement this with this control.

**Comment by AJIXuMuK** [comment]
Thank you @lafe for reporting and implementing the enhancement!
It will be included in the next release.
