### ISSUE TITLE
PropertyFieldViewPicker - Unable to load Views from another site

### ISSUE THREAD

**Issue by frankok** [pnp/sp-dev-fx-property-controls#263]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [    1.18.0     ]

#### Expected / Desired Behavior / Question
I have a web part with Site Url, PropertyFieldListPicker and PropertyFieldViewPicker. When a Site Url is set, the List Picker displays the lists from that site (using the webAbsoluteUrl property). 
Expected this also to be the case with the View Picker.

#### Observed Behavior
Even if webAbsoluteUrl is set (to another site other than the current site), it does not load the views for the selected list in the List Picker.

![image](https://user-images.githubusercontent.com/20436301/84074782-63749600-a9d3-11ea-975a-c5a49bb94058.png)

Error message from console:

  | (anonymous) | @ | PropertyFieldViewPickerHost.js:62
-- | -- | -- | --
  | Promise.then (async) |   |  
  | sch4.PropertyFieldViewPickerHost.loadViews | @ | PropertyFieldViewPickerHost.js:60
  | sch4.PropertyFieldViewPickerHost.componentDidMount | @ | PropertyFieldViewPickerHost.js:45
  | Na | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Ma | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | (anonymous) | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | t.unstable_runWithPriority | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | To | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | xo | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | bo | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | mo | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Wa | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Co | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Po | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Do.render | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | (anonymous) | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Eo | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Uo | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | render | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | (anonymous) | @ | sp-property-pane_en-…7257c0677c6da0.js:1
  | Promise.then (async) |   |  
  | e._loadPropertyPaneComponent | @ | sp-property-pane_en-…7257c0677c6da0.js:1
  | e._buildAndLoadPropertyPane | @ | sp-property-pane_en-…7257c0677c6da0.js:1
  | (anonymous) | @ | sp-property-pane_en-…7257c0677c6da0.js:1
  | Promise.then (async) |   |  
  | e._renderPropertyPane | @ | sp-property-pane_en-…7257c0677c6da0.js:1
  | e._executeAction | @ | sp-property-pane_en-…7257c0677c6da0.js:1
  | e.requestAction | @ | sp-property-pane_en-…7257c0677c6da0.js:1
  | e.requestPropertyPaneAction | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | n.handleConfigureButtonClicked | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | handleConfigureButtonClicked | @ | chunk.sp-canvas-edit…01ad640fa1e1b2.js:1
  | onClick | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | u | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | m | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | (anonymous) | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | S | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | O | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | P | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | D | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | En | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | _o | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Le | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | On | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | (anonymous) | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | t.unstable_runWithPriority | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | So | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1
  | Nn | @ | sp-webpart-workbench…d8c6b3cd80d4e2.js:1

#### Steps to Reproduce
Add the following controls to a web part:
Site Url - Text Field
List - PropertyFieldListPicker 
View - PropertyFieldViewPicker

When Site Url is set to another site than the current site, views fail to load based on the selected List.

**Comment by frankok** [comment]
Hi, no feedback on this issue yet. 
@hugoabernier, do you have any feedback on this?

**Comment by frankok** [comment]
Hi again,
I downloaded the source code, and added the ViewPicker to my project. 
After debugging, I tested with adding the following:

    webAbsoluteUrl: properties.webAbsoluteUrl,

I added it (on line 135) in the export function PropertyFieldViewPicker in PropertyFieldviewPicker.ts.
This seems to do the trick.

**Comment by hugoabernier** [comment]
@frankok thanks for reporting this. Sorry, with the massive numbers of emails I get from GitHub, this one slipped through the cracks.

Working on a PR to include your fix. Thank you!

**Comment by AJIXuMuK** [comment]
Hi @frankok!
Thank you for reporting this one!
@hugoabernier made the fix and it'll be included in the next release.
In a meanwhile you can test it in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/).
