### ISSUE TITLE
 roleDefinition picker

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-property-controls#266]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [x ] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [   latest      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

Hey , it would be nice to have a roleDefinition picker. So if an app wants to grant a specific permission we could have a picker that lets you specify what permission level to use.
for valid options we could use pnpjs sp.web.roleDefinitions()

Thanks!

**Comment by gautamdsheth** [comment]
@AJIXuMuK - picking this up. Hope that's fine :)

**Comment by AJIXuMuK** [comment]
Implemented in #268
