### ISSUE TITLE
PropertyFieldListPicker has no feature of Default checking option.

### ISSUE THREAD

**Issue by SaiKiranChowdam** [pnp/sp-dev-fx-property-controls#267]
Hi ,
I have a requirement where i need to all lists from a library and PropertyFieldListPicker is the best fit for my requirement but it has no option of default checking .

When Propertypane loads,  the PropertyFieldListPicker showing options but there is no option to preSelect / PreCheck the options that are populated.

It would be great if there's a solution for that.

Thanks.

**Comment by AJIXuMuK** [comment]
Hi @SaiKiranChowdam!
As any other Property Control, `PropertyFieldListPicker` gets value from the web part `properties` based on `targetProperty` value provided during the initialization.

For example,
```typescript
export interface IYourWebPartProps {
  lists: string | string[];
}

//...

PropertyFieldListPicker('lists', {
  //...
}
```

So, if `this.properties.lists` has value, it will be displayed in the picker.

For your scenario I would pre-initialize `this.properties` in web part's manifest.

**Comment by ZabbyCapurin** [comment]
I just tried the suggestion, but it doesn't work very well if you don't know the GUID beforehand
