### ISSUE TITLE
[Documentation] Link to PropertyFieldListPicker control points to PropertyFieldMessage

### ISSUE THREAD

**Issue by joshtransient** [pnp/sp-dev-fx-property-controls#269]
#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: latest/current documentation on https://pnp.github.io/sp-dev-fx-property-controls/

#### Expected / Desired Behavior / Question
Navigate to Controls, then PropertyFieldListPicker, get sent to PropertyFieldListPicker page.

#### Observed Behavior
Get sent to PropertyFieldMessage page.

#### Steps to Reproduce
Visit https://pnp.github.io/sp-dev-fx-property-controls/, click Controls > PropertyFieldListPicker

**Comment by AJIXuMuK** [comment]
@joshtransient  - thank you for pointing this out!

The fix will be available in the next version.
