### ISSUE TITLE
New Control -- Folder Picker

### ISSUE THREAD

**Issue by russgove** [pnp/sp-dev-fx-property-controls#272]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [         ]

latest

#### Expected / Desired Behavior / Question
It would be nice if we could have a folder picker control. Admin would select whether he wants a folder in a list/library or either. Admin could then drill into the SP folder structure to select the exact folder where the webpart would get or put listitems or documents. Perhaps this could be built into the list picker or a separate control.

**Comment by gautamdsheth** [comment]
Picking this up !

**Comment by AJIXuMuK** [comment]
Hi @russgove!
@gautamdsheth has implemented the component. It will be available in the next release.
In a meantime you can test it in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/).
