### ISSUE TITLE
Configure for Date Picker only?

### ISSUE THREAD

**Issue by voltmer1** [pnp/sp-dev-fx-property-controls#275]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category

- [x] Question

#### Version

Please specify what version of the library you are using: [   1.8.2      ]

#### Expected / Desired Behavior / Question

On the documentation webpage: [https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldDateTimePicker/].
It is stated that this may be configured to display only the date picker, but there isn't any property to enable this? How is this achieved?

**Comment by AJIXuMuK** [comment]
Hello @voltmer1!
You should use `dateConvention` proprety of the component and set it to `DateConvention.Date`.
