### ISSUE TITLE
IDateTimeFieldValue "value" issue

### ISSUE THREAD

**Issue by voltmer1** [pnp/sp-dev-fx-property-controls#279]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [x ] Question

#### Version
Please specify what version of the library you are using: [ 1.8.2 ]

#### Expected / Desired Behavior / Question
the IDateTimeFieldValue object has "value", which is type Date, but you cannot date.value.toISOString(), so I tried date.value.slice() thinking it was already a string, but no. Compiler says it's a Date. I need it as a string to slice it. what should I do? Is this a bug?

**Comment by AJIXuMuK** [comment]
`this.properties.date.value.toISOString()` works correctly for me.
And the `value` is `Date`:
![date](https://user-images.githubusercontent.com/17036219/89491960-4a832980-d765-11ea-83b8-7db709dcfa16.png)

Could you please try to update to the latest version and check if that solves the issue?

**Comment by voltmer1** [comment]
I see what is causing the issue. If you select a date from the picker and then select a different one the original date is no longer a Date object, but a string, so in ComponenentDidUpdate I was assuming that both the new date and the previous date would both be Date objects, so I was converting them to ISO Strings, which is not possible on the original date, that is already a ISO String. Does the picker convert the this.props.date.value to a string at any point?

**Comment by AJIXuMuK** [comment]
@voltmer1 the component doesn't process the original date.
We just use what was set to `initialDate` property.

Could you please check that `initialDate` is set correctly and you don't change `value` property of it?

**Comment by voltmer1** [comment]
I believe I've set the property correctly (see below). I never reference the initialDate property anywhere else in my code, so the value property would never be altered.

PropertyFieldDateTimePicker("date", {
                  label: strings.DateFieldLabel,
                  initialDate: this.properties.date,
                  dateConvention: DateConvention.Date,
                  timeConvention: TimeConvention.Hours12,
                  onPropertyChange: this.onPropertyPaneFieldChanged,
                  properties: this.properties,
                  onGetErrorMessage: null,
                  deferredValidationTime: 0,
                  key: "dateTimeFieldId",
                  showLabels: false,
                }),

**Comment by AJIXuMuK** [comment]
@voltmer1 this one looks correct.

Could you please provide the code where you're experiencing the issue?
