### ISSUE TITLE
PropertyFieldListPicker control to return Title or relative URL

### ISSUE THREAD

**Issue by RA1449** [pnp/sp-dev-fx-property-controls#281]
#### Category
- [X ] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [   1.19.0    ]

####  Desired Behavior 
It would be great if the PropertyFieldListPicker control returned the list/library Title or relative URL.  Some SharePoint APIs don't use guids.

**Comment by AJIXuMuK** [comment]
Thank you @RA1449 for the idea!

We'll look into it!

**Comment by ArndBrugman** [comment]
This is exactly what I was looking for, by using the ByName on the configuration I can use the page as a template over multiple site collections. This is inhibited by used the unique ID. Would be a great addition as I now have a lot of custom code in my solution that I would love to replace with using a component that uses the List Title as a key. Could be a configuration option if I'm right?

**Comment by AJIXuMuK** [comment]
@RA1449, @ArndBrugman - this has been implemented and will be included in the next release.

There is a new property `includeListTitleAndUrl`. If it is set to `true` the picker will return `IPropertyFieldList` objects:

```typescript
/**
 * Detailed list information
 */
export interface IPropertyFieldList {
  /**
   * List ID
   */
  id: string;
  /**
   * List Title
   */
  title?: string;
  /**
   * List server relative URL
   */
  url?: string;
}
```

You can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/)
