### ISSUE TITLE
PropertyFieldNumber give "Maximum update depth exceeded" error

### ISSUE THREAD

**Issue by albegut** [pnp/sp-dev-fx-property-controls#282]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

 [1.19.0]

#### Expected / Desired Behavior / Question
Set the PropertyFieldNumber to empty.

#### Observed Behavior
Fatal error if the field data is deleted. Same issue as #258 

#### Steps to Reproduce
I am using PropertyFieldNumber in my webpart. When updating the field it disappears and gives me the following error in the console log: https://reactjs.org/docs/error-decoder.html/?invariant=185 

To reproduce this error try following configuration:

```
PropertyFieldNumber("SiteNameOrder", {
                    key: "SiteNameOrder",
                    label: "Site column Order",
                    description: "Order of site title column",
                    value: this.properties.SiteNameOrder,
                    disabled: !this.properties.ShowSiteTitle
                  })
```

And add some text in the field before removing it

![PropertyFieldNumber](https://user-images.githubusercontent.com/9661096/90548042-abaaf400-e18c-11ea-873b-97a96c839cf5.gif)

**Comment by albegut** [comment]
It's partilly fixed if you set null as value when the property is empty

```
PropertyFieldNumber("SiteNameOrder", {
        key: "SiteNameOrder",
        label: "Site column Order",
        description: "Order of site title column",
        value: this.properties.SiteNameOrder || null,
        disabled: !this.properties.ShowSiteTitle
      })
```

![PropertyFieldNumber (1)](https://user-images.githubusercontent.com/9661096/90550641-861fe980-e190-11ea-99f7-7142aa7b6ab7.gif)

**Comment by AJIXuMuK** [comment]
Hi @albegut!
Thank you for reporting this bug!
It has been fixed and will be available in the next release.
In a meantime you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/)
