### ISSUE TITLE
PropertyFieldCollectionData onCustomRender shows required field validation row error after value selects

### ISSUE THREAD

**Issue by pk091990** [pnp/sp-dev-fx-property-controls#284]
#### Category
- [ ] Enhancement
- [*] Bug
- [ ] Question

#### Version :

Please specify what version of the library you are using: ^1.19.0

#### Expected / Desired Behavior / Question
I've created custom combobox with oob number field and need to show required field validation when there is no value in the controls. However its working just opposite for the custom control. When there is no value in the custom control, it shows me no row error (may be because I've not handled null condition in my code) but as soon as I select any value from dropdown it shows error but still save the record when I save it.

Screenshots:

When no value selected in custom field:
![image](https://user-images.githubusercontent.com/46436213/91017195-81818800-e60b-11ea-836b-c750318c4085.png)

When value selected in custom field:
![image](https://user-images.githubusercontent.com/46436213/91017273-a413a100-e60b-11ea-805b-29bf88bd7290.png)

Code:
![image](https://user-images.githubusercontent.com/46436213/91017435-df15d480-e60b-11ea-8c8a-b6af08ecb054.png)

Please correct me I'm doing anything wrong here!

**Comment by AJIXuMuK** [comment]
Hi @pk091990!
Thanks for reporting this one!
The documentation was not completely correct: you need to call `onUpdate` **prior** to `onError`.
In that case everything will work as expected.

I've updated the docs. They will be published with the next release.

Let us know if there are any other issues.
