### ISSUE TITLE
New control : GUID

### ISSUE THREAD

**Issue by anoopt** [pnp/sp-dev-fx-property-controls#286]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Expected / Desired Behavior / Question
Is it worth having a property pane control which will accept only valid GUID? 

If yes, I am happy to work on this.

*Sample scenario* - ID of a termset is needed by a webpart so that the related terms can be fetched [example - this webpart](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-graph-cascading-managed-metadata)

**Comment by AJIXuMuK** [comment]
Hi @anoopt!

If it's needed once, there will be others who'll benefit from such a control.
So feel free to implement it!

**Comment by anoopt** [comment]
Thank you @AJIXuMuK I will work on it.
