### ISSUE TITLE
PropertyFieldCollectionData with column type of PropertyFieldCodeEditor 

### ISSUE THREAD

**Issue by svermaak** [pnp/sp-dev-fx-property-controls#287]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [ x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [Latest ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_
It would be extremely useful if PropertyFieldCollectionData could have a column type for PropertyFieldCodeEditor 

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._
NA

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._
NA

**Comment by AJIXuMuK** [comment]
Hi @svermaak,

Thanks for the idea.

But Property controls can't contain other property controls.

You can still implement (partially copy-paste) Code Editor control and inject in it `PropertyFieldCollectionData` using `custom` type
