### ISSUE TITLE
PropertyFieldListPicker link has wrong url

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/sp-dev-fx-property-controls#293]
#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 1.18.0]

#### Expected / Desired Behavior / Question
When I went to url https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldCodeEditor/ & then clicked on PropertyFieldListPicker, It should show me details about PropertyFieldListPicker

#### Observed Behavior
When clicking on PropertyFieldListPicker, It is showing details about PropertyFieldMessage

#### Steps to Reproduce
Go to https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldCodeEditor/
Click on PropertyFieldListPicker

**Comment by AJIXuMuK** [comment]
Thanks @gauravgoyal5 for reporting this.

The issues has already been addressed.
