### ISSUE TITLE
Propertyfield file picker not getting org assets library

### ISSUE THREAD

**Issue by bargshree** [pnp/sp-dev-fx-property-controls#295]
#### Category
- [ ] Enhancement
- [**X** ] Bug
- [ ] Question

#### Version
1.20.0

#### Expected / Desired Behavior / Question
Your Organization tab is visible to pick and choose files from the org assets library
#### Observed Behavior
Your Organization tab is not visible

#### Steps to Reproduce

- A library has been designated as org assets library, and can be seen when using OOTB image webpart
- Create a new webpart, import PropertyFieldFilePicker and add it as a webpart property
- All other options (one drive, site, recent etc..) are visible, but only 'Your Organization' is missing

While debugging, getting an error on this line - OrgAssetsService.ts - getSiteMediaLibraries - line 52. REST API query is unsuccessful with error code 500.
![image](https://user-images.githubusercontent.com/27858873/92677566-ca427c00-f341-11ea-8aa8-d83baf47b8a7.png)

None of the end users are going to be tenant admin, in order for this REST API call to be successful.
_**/_api/Microsoft.Online.SharePoint.TenantManagement.Office365Tenant/GetOrgAssets**_

Thanks!
Bargavi

**Comment by AJIXuMuK** [comment]
Thanks @bargshree for reporting the issue!
@gautamdsheth has added the PR with the fix.
It will be available in the next release.
In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/)

**Comment by kodofix** [comment]
@AJIXuMuK just kindly ask if it's possible to merge this fix into version which support on premise as well? I just facing exactly this issue right now?

Thank you in advance for your hard work
