### ISSUE TITLE
Opton to disable selection of terms in TermPicker 

### ISSUE THREAD

**Issue by wilecoyotegenius** [pnp/sp-dev-fx-property-controls#307]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 2.0.0 ]

#### Expected / Desired Behavior / Question
Currently, PropertyFieldTermPicker allows you to choose if selecting term sets is possible, but there is no way to choose, if terms should be selectable or not. And in some cases, user needs to specify just the term set, not term.
I propose adding _isTermSelectable_ property that would specify, whether individual terms could be selected.

If you find this enchancement useful, I'll be happy to work on this.

**Comment by AJIXuMuK** [comment]
Hi @wilecoyotegenius,

Could you please describe your use-case a bit more? Do you actually want to see the terms but be unable to select them? Or you just want to see term sets, without terms?

**Comment by wilecoyotegenius** [comment]
@AJIXuMuK I was thinking about the latter - just seeing and being able to select term sets

**Comment by wilecoyotegenius** [comment]
@AJIXuMuK If you like the idea, I'd be happy to submit a PR for this.

**Comment by AJIXuMuK** [comment]
Hi @wilecoyotegenius,

Feel free to submit a PR! I would probably implement two separate flags: one to disable terms selection and another to hide terms.
