### ISSUE TITLE
Add CodeEditor 'wrapEnabled' property

### ISSUE THREAD

**Issue by kflogdev** [pnp/sp-dev-fx-property-controls#316]
#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

[2.2.0 ]

#### Expected / Desired Behavior / Question
It would be great to have a boolean property on the CodeEditor control that allows us to set the [wrapEnabled](https://github.com/securingsincity/react-ace/blob/master/docs/Ace.md) property for line wrapping.

I would be happy to submit a PR for this additional property.

**Comment by AJIXuMuK** [comment]
Hi @kflogdev,

Sure - feel free to submit a PR!

Please, do not forget to reference `dev` branch for the PR.

**Comment by AJIXuMuK** [comment]
The PR with enhancement has been merged and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by AJIXuMuK** [comment]
`v2.4.0` has been released.
