### ISSUE TITLE
PropertyFieldColumnPicker?

### ISSUE THREAD

**Issue by jscudder** [pnp/sp-dev-fx-property-controls#317]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [   2.1.1      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Any plans to implement a List column picker dependent on list similar to the PropertyFieldListPicker which is optionally dependent on site?

**Comment by AJIXuMuK** [comment]
Hi @jscudder,
It could be a good addition to the library!

Thank you for the suggestion.

**Comment by sudharsank** [comment]
Hi @AJIXuMuK, I am interested to take this enhancement. Please let me know.

**Comment by AJIXuMuK** [comment]
Sure @sudharsank! Thank you!

**Comment by sudharsank** [comment]
Hi @jscudder, the control is released. Hope you had already tried the control? Let us know if you have any issues.

**Comment by vamsi981** [comment]
Unable to add Filter through filter property  Below is what it is going through browser
<img width="647" alt="Screenshot 2021-04-29 at 3 35 29 PM" src="https://user-images.githubusercontent.com/881555/116535103-ffb3ce00-a900-11eb-8f74-2a5f356ab3df.png">

Filter not working properly and debugged the found the following error in the code 
"SPColumnPickerService.js"

`if (this.props.filter) {
                            if (displayHiddenColumns)
                                queryUrl += "&$filter=&" + encodeURIComponent(this.props.filter);
                            else
                                queryUrl += "&$filter=Hidden eq false&" + encodeURIComponent(this.props.filter);
                        }`

above code `&` should be removed other wise it will be treated as new Query string.

**Comment by joelfmrodrigues** [comment]
@jscudder closing this item as the control is now available.
Many thanks for your contribution

**Comment by joelfmrodrigues** [comment]
@sudharsank Thanks a lot!

**Comment by joelfmrodrigues** [comment]
@vamsi981 I noticed that you created a new issue for the problem described above, so this item will now be closed
