### ISSUE TITLE
PropertyFieldIconPicker?

### ISSUE THREAD

**Issue by jscudder** [pnp/sp-dev-fx-property-controls#318]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [ X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [   2.2.0      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Are there any plans to develop a PropertyFieldIconPicker with the same UI as https://pnp.github.io/sp-dev-fx-controls-react/controls/IconPicker/ ?

**Comment by gautamdsheth** [comment]
Happy to pick it up.
@AJIXuMuK - can you please assign it to me ?

**Comment by AJIXuMuK** [comment]
I can't set you as assignee, but you got it :)

**Comment by AJIXuMuK** [comment]
@jscudder - @gautamdsheth has implemented the component.
It will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/)

**Comment by jscudder** [comment]
This is outstanding. Thank you
