### ISSUE TITLE
PropertyFieldCollectionData Dropdown validation not working as expected

### ISSUE THREAD

**Issue by Dave-Buck** [pnp/sp-dev-fx-property-controls#321]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
2.2.0 (SPFx v1.11.0, Node v10.22.1)

#### Issue
When using the `PropertyFieldCollectionData` property pane control, `onGetErrorMessage` is not triggered for `CustomCollectionFieldType.dropdown`, resulting in no error message telling the user that the field is required, but you are not able to 'Add and Save' the collection item.

#### Expected behaviour
Each time the `CustomCollectionFieldType.dropdown` is changed, `onGetErrorMessage` is also triggered. When the dropdown is blank, the error message shows.

#### Observed Behavior
On load (when my dropdown is blank), no error message is shown (dropdown is required), see below:
![image](https://user-images.githubusercontent.com/33024481/103782189-0d320900-502f-11eb-8495-2eb3e695aacc.png)

But I am not able to save the item, meaning that it is actually required, but there is no user feedback. This behaviour works fine for standard string fields. Am I missing something? Also, when dropdown value is changed, `onGetErrorMessage` is not triggered.

[Stack Exchange Question](https://sharepoint.stackexchange.com/questions/288458/ongeterrormessage-for-propertyfieldcollectiondata-customcollectionfieldtype-drop) outlining the exact issue in case my explanation was poor.

#### Steps to Reproduce
Create a new SPFx module with a `PropertyFieldCollectionData` property pane control that has a required dropdown. 

Let me know if you need any further information.

Thanks in advance!

**Comment by AJIXuMuK** [comment]
Hi @Dave-Buck,
Thank you for reporting this!

The fix has been merged and will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by Dave-Buck** [comment]
Thanks @AJIXuMuK, much appreciated!

**Comment by joelfmrodrigues** [comment]
@Dave-Buck closing this item as it should be resolved now. Please open a new issue if you still experience problems with the latest release.
Thanks for your contribution

**Comment by kodofix** [comment]
@AJIXuMuK any chance to merge that to version supporting on-premise, even if release of on-premise version can take a while?
