### ISSUE TITLE
Support for a Color Picker control within the PropertyFieldCollectionData property pane control.

### ISSUE THREAD

**Issue by johnnycardy** [pnp/sp-dev-fx-property-controls#326]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Expected / Desired Behavior / Question
The PropertyFieldCollectionData control by default has some sub-controls for its property editing. 
Suggestion is to support a swatch color picker as the control (to be added to CustomCollectionFieldType). See PropertyFieldSwatchColorPicker as an example of what it would look like.

**Comment by johnnycardy** [comment]
I now have this implemented and it looks like the below, feedback welcome! PR incoming...

![image](https://user-images.githubusercontent.com/904610/106673760-0785ff80-65aa-11eb-9a5d-2485875cbd96.png)

**Comment by AJIXuMuK** [comment]
Thank you @johnnycardy for submitting the idea and implementing it!

It will be included in the next release.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by AJIXuMuK** [comment]
`v2.4.0` has been released.
