### ISSUE TITLE
PropertyFieldMultiSelect callout rendering with many options

### ISSUE THREAD

**Issue by beats-lvt** [pnp/sp-dev-fx-property-controls#328]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question

#### Version

>2.0.0

#### Expected / Desired Behavior / Question
The callout containing the options renders directly below the dropdown control (like in version < 1.20.0

#### Observed Behavior
The callout containing the options is starting from top of the property pane.
adding calloutProps: { calloutMaxHeight: <any positive number> } renders the callout at the correct position, but the height is no longer calculated automatically.

#### Steps to Reproduce
- add PropertyFieldMultiSelect to the property pane
- set items to an string[] with more than 30 items

#### Submission Guidelines
version 1.x is not affected 
(we are planning to upgrade from 1.20 to 2.3)

**Comment by AJIXuMuK** [comment]
Hi @beats-lvt,

Thank you for reporting this!
Unfortunately, it's a standard behavior of Fluent UI Dropdown - it tries to use as much vertical space as possible.
Here is the sample of Fluent UI Dropdown (the third one is opened):

<img width="681" alt="Screen Shot 2021-02-08 at 5 08 28 PM" src="https://user-images.githubusercontent.com/17036219/107301427-514e6a00-6a30-11eb-9896-031a90af65f0.png">


If you provide custom height, that is less than offset from dropdown location to the bottom of the page/container, it will render as you wish.

But it is not something that we can fix in the library.
