### ISSUE TITLE
SitePicker issue for Single Select when multiple search results are webs under single parent

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-property-controls#329]
@AJIXuMuK , Tried tagging Niels Soeth but does not seem like his account is still active.

#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
"@pnp/spfx-property-controls": "^2.3.0",

#### Expected / Desired Behavior / Question
When I set component **multiSelect: false,** it should only select one site in the results returned from search.

#### Observed Behavior
When I have searched and found 3 sites, I check one box but 3 get selected in the pick list.
However, in the Websites selected, it shows the one I clicked.

![image](https://user-images.githubusercontent.com/49648086/107385621-0df00c00-6ac1-11eb-8472-f4f23d7c0ae3.png)

#### Steps to Reproduce
It doesn't seem to be consistent for me on every search.
It **does seem to** happen when multiple sites with same search criteria are found as subsites under a single parent site.
In my screenshot where I search for **track**, the 3 selected are under the same parent site collection.

![image](https://user-images.githubusercontent.com/49648086/107385588-07619480-6ac1-11eb-8dee-d2cbb36ca3bd.png)

**Comment by AJIXuMuK** [comment]
Good catch @mikezimm!


The fix has been merged and will be included in the next release.
Additionally, you will find new `webId` property in the selected `site` object.

In a meanwhile you can test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by AJIXuMuK** [comment]
`v2.4.0` has been released.
