### ISSUE TITLE
Support Page Environment dynamic properties on PropertyPanePropertyEditor

### ISSUE THREAD

**Issue by wobba** [pnp/sp-dev-fx-property-controls#331]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [2.3.0]

#### Expected / Desired Behavior / Question
Right now all `DynamicProperty` settings are ignored on import. For `WebPart` ones it might make sense as id's are changing. For `PageContext` ones they should work as they exist everywhere.

https://github.com/pnp/sp-dev-fx-property-controls/blob/master/src/propertyFields/propertyEditor/PropertyPanePropertyEditorHost.tsx#L46

We would like to use this for the PnP Modern Search web parts, at least for scenarios where page context dynamic data is consumed.

#### Observed Behavior
`PageContext` dynamic properties are being ignored on `Apply` when importing web part properties.

#### Steps to Reproduce
Import settings with dynamic data and they are not set.

**Comment by AJIXuMuK** [comment]
Hi @wobba,
Thanks for reporting this one.

There was an [issue](https://github.com/pnp/sp-dev-fx-property-controls/issues/200) that dynamic properties are causing issues. So, we disabled them.

I'll take a look if I can come up with some alternative approach.

**Comment by AJIXuMuK** [comment]
@wobba I've implemented the change.

Could you please test it in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/)?

**Comment by wobba** [comment]
@AJIXuMuK sure thing - I'll let you know.

**Comment by wobba** [comment]
@AJIXuMuK works like expected :) Thank you.

**Comment by AJIXuMuK** [comment]
`v2.4.0` has been released.
