### ISSUE TITLE
Import from root causes unhelpful error message in SP / workbench

### ISSUE THREAD

**Issue by t0mgerman** [pnp/sp-dev-fx-property-controls#334]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Version
2.3.0

#### Expected / Desired Behavior / Question
This is a bit of a RTFM thing I suppose. It appears the index of `@pnp/spfx-property-controls` is exporting many of the controls, such as `PropertyFieldMultiSelect` for example... if you attempt to import from here rather than the correct path of `@pnp/spfx-property-controls/lib/PropertyFieldMultiSelect` this causes an error that users may spend time erroneously trying to debug. My question is - is there a reason it's set up this way? Conscious that there may well be.

#### Observed Behavior
SPFX Workbench gives blue "Something went wrong" screen, with triggering error being: 

```Object prototype may only be an Object or null: undefined```

#### Steps to Reproduce
Create a new project with `yo @microsoft/sharepoint` or `yo @pnp/spfx` and attempt to add one of the property controls using an import from `@pnp/spfx-property-controls` ie.
```ts
import { PropertyFieldMultiSelect } from '@pnp/spfx-property-controls';
```

Apologies if this is a silly question - I only raise it as one of my colleagues spent a fair bit of time trying to debug the error before we figured out what was going on. Seems like an easy mistake to make if skimming the docs as intellisense can make you think the import is possible.

**Comment by AJIXuMuK** [comment]
Hi @t0mgerman,
I can't repro this issue.
`import { PropertyFieldMultiSelect } from '@pnp/spfx-property-controls';` works fine.

Could you please check what versions of devtools you're using? Node/npm, Gulp?
