### ISSUE TITLE
PropertyFieldSitePicker context property expects IWebPartContext

### ISSUE THREAD

**Issue by mrcpgn** [pnp/sp-dev-fx-property-controls#335]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
@pnp/spfx-property-controls 2.3.0

#### Expected / Desired Behavior / Question
PropertyFieldSitePicker('sites', {
                  ....
                  context: this.context,
                  ...
                })
context in PropertyFieldSitePicker would map to WebPartContext.

#### Observed Behavior
`Type 'WebPartContext' is not assignable to type 'IWebPartContext'.
  Types of property 'httpClient' are incompatible.
    Type 'import("d:/....../node_modules/@microsoft/sp-http/dist/index-internal").HttpClient' is not assignable to type 'import("d:/......./node_modules/@pnp/spfx-property-controls/node_modules/@microsoft/sp-http/dist/index-internal").HttpClient'.
      Types have separate declarations of a private property '_fetchProvider'.ts(2322)
IPropertyFieldSitePicker.d.ts(32, 5): The expected type comes from property 'context' which is declared here on type 'IPropertyFieldSitePickerProps'`

#### Steps to Reproduce
Install the packages.
Add the imports, etc.
Add the PropertyFieldSitePicker sample code to the existing groupFields collection.

Thanks!

**Comment by Dangerous-Mind** [comment]
Any news on this issue? Version 2.5 has the same problem.

**Comment by mcmpistachio** [comment]
I'm seeing the same issue on the PropertyFieldPeoplePicker with the WebPartContext is not assignable to the BaseComponentContext. Any work arounds that could shed some light on other issues of context?

**Comment by AJIXuMuK** [comment]
Hi @mrcpgn,

What version of SPFx are you using? Are you on-prem or online?

**Comment by mrcpgn** [comment]
> Hi @mrcpgn,
> 
> What version of SPFx are you using? Are you on-prem or online?

Hi @AJIXuMuK,
1.10.0 - online.

**Comment by AJIXuMuK** [comment]
`v2` of controls has a dependency on SPFx `v1.11`.
So, my suggestion is either use controls `v1` or (better in all ways) - upgrade to SPFx `v1.11`.

**Comment by mrcpgn** [comment]
thanks @AJIXuMuK, I will try to update to version 1.11 and give you feedback

**Comment by AJIXuMuK** [comment]
Any updates @mrcpgn?
