### ISSUE TITLE
Solution sample for PropertyFieldFilePicker?

### ISSUE THREAD

**Issue by sbn11** [pnp/sp-dev-fx-property-controls#336]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Version
[2.3.0]

#### Question
Do you have a complete Sample how to use the PropertyFieldFilePicker? I can't get it working, but not sure if it's a bug or I'm doing something wrong. Please advise.

#### Observed Behavior
After importing the component and adding the Property as intended I get this error:
Type 'IPropertyPaneField<IPropertyFieldFilePickerPropsInternal>' is not assignable to type 'IPropertyPaneField<any>'.
![image](https://user-images.githubusercontent.com/67097539/108991759-c52b7c00-7698-11eb-8f75-f14052b5f932.png)

Thanks!

**Comment by sudharsank** [comment]
Hi @sbn11, I wrote a blog post on how to use the FilePicker & FileTypeIcon. I hope that would resolve your issue.
[SPFx Using FilePicker & FileTypeIcon](https://spknowledge.com/2020/02/29/spfx-using-filepicker-and-filetypeicon-control/)

**Comment by sbn11** [comment]
Thank you @sudharsank.
Meanwhile I figured it out. The Properties don't work with SP onprem, I didn't see this at first. Thanks though.
