### ISSUE TITLE
Property Field Number round value on construction

### ISSUE THREAD

**Issue by TheThor59** [pnp/sp-dev-fx-property-controls#344]
Hello,

The property field number is loosing decimal value on futher edits of the properties.

#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version

Version in use is 2.4.0

#### Expected
According to documentation, using the component PropertyFieldNumber without setting property "precision" let the decimal unchanged and not rounded.

#### Observed Behavior
I'm using last version (2.4) of the components and as I was using the Property Field Number, I encountered an issue. Not setting the precision value and setting the value as decimal work perfectly when editing the web part. But when saving page, and coming back on the options the decimal is lost.

#### Steps to Reproduce
Create a web part with a number property and use a PropertyFieldNumber to set it's value in the web part property pane, do not set precision property. Set the value to a decimal number, save refresh the page and edit back the properties. Example of property configuration :
```javascript
PropertyFieldNumber('DecimalValue', {
                  label: "Decimal",
                  minValue: 0,
                  maxValue: 100,
                  key: "decimalvalue",
                  value: this.properties.DecimalValue,
                })
```

#### Submission Guidelines
The issue is due to the file PropertyFieldNumberHost where, in the constructor line 20 the state of this component is set :
```javascript
this.state = {
      value: this.props.value ? this.props.value.toFixed(props.precision || 0) : null,
      roundedValue: props.value
    };
```

When using this, a round is done between precision set by user, and 0. This means that when we do not set any precision, the component will consider that it's equal to precision = 0, resulting in losing of the decimal information. Only workaround for now is to set a prevision with high value (like 10) but might not fit all scenarios.

Thanks!

**Comment by TheThor59** [comment]
I'm adding a point, if you set value to 0, the code initializing the component do a wrong test :
```javascript
value: this.props.value ? this.props.value.toFixed(props.precision || 0) : null,
```
The test on this.props.value is false if value is equal to 0, as a result an error message appear that my field is not a number.

**Comment by AJIXuMuK** [comment]
Thank you @TheThor59 for reporting this one!
The fix has been implemented and will be included in the next release.

In a meanwhile you can test it in [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/)

**Comment by TheThor59** [comment]
Thanks for the help, I was working on a fix and got a conflict juste before pushing PR and didn't notice your message.

Thanks for the quick fix.

Regards.

**Comment by TheThor59** [comment]
Hello I created a new pull request as half of the issue was not fixed

**Comment by AJIXuMuK** [comment]
The fix is in `dev` and should be soon available in beta version.
