### ISSUE TITLE
SPFx 1.12 type clash issue

### ISSUE THREAD

**Issue by weshackett** [pnp/sp-dev-fx-property-controls#346]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [    "@pnp/spfx-property-controls": "2.4.0",     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Observed Behavior

Error while running Gulp Build

[19:07:48] Error - [tsc] src/webparts/fgdf/FgdfWebPart.ts(57,19): error TS2322: Type 'import("C:/Repos/dfgdf/node_modules/@microsoft/sp-webpart-base/dist/index-internal").WebPartContext' is not assignable to type 'import("C:/Repos/dfgdf/node_modules/@pnp/spfx-property-controls/node_modules/@microsoft/sp-webpart-base/dist/index-internal").WebPartContext'.
[19:07:48] [tsc] Types have separate declarations of a private property '_domElement'.

#### Steps to Reproduce

To reproduce:

1. Update SPFx env to use 1.12 per MS instructions
2. Run new webpart from Yo
3. Install the PnP Property Controls from Npm 'npm install @pnp/spfx-property-controls --save --save-exact'
4. Add a property to the default web part

```typescript
import * as React from 'react';
import * as ReactDom from 'react-dom';
import { Version } from '@microsoft/sp-core-library';
import {
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-property-pane';
import { BaseClientSideWebPart } from '@microsoft/sp-webpart-base';

import * as strings from 'FgdfWebPartStrings';
import Fgdf from './components/Fgdf';
import { IFgdfProps } from './components/IFgdfProps';

import { PropertyFieldFilePicker, IPropertyFieldFilePickerProps, IFilePickerResult } from "@pnp/spfx-property-controls/lib/PropertyFieldFilePicker";

export interface IFgdfWebPartProps {
  description: string;
  filePickerResult: IFilePickerResult;
}

export default class FgdfWebPart extends BaseClientSideWebPart<IFgdfWebPartProps> {

  public render(): void {
    const element: React.ReactElement<IFgdfProps> = React.createElement(
      Fgdf,
      {
        description: this.properties.description
      }
    );

    ReactDom.render(element, this.domElement);
  }

  protected onDispose(): void {
    ReactDom.unmountComponentAtNode(this.domElement);
  }

  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('description', {
                  label: strings.DescriptionFieldLabel
                }),
                PropertyFieldFilePicker('filePicker', {
                  context: this.context,
                  filePickerResult: this.properties.filePickerResult,
                  onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
                  properties: this.properties,
                  onSave: (e: IFilePickerResult) => { console.log(e); this.properties.filePickerResult = e;  },
                  onChanged: (e: IFilePickerResult) => { console.log(e); this.properties.filePickerResult = e; },
                  key: "filePickerId",
                  buttonLabel: "File Picker",
                  label: "File Picker",                  
              })
              ]
            }
          ]
        }
      ]
    };
  }
}
```

5. Run gulp build
6. Error shown

**Comment by ColinGardner** [comment]
With SPFx 1.12 currently withdrawn and for anyone still experiencing this issue I have discovered you can just effectively ignore it  with:
 // @ts-ignore
 context: this.context,
