### ISSUE TITLE
Adding debounce property to ColorPicker

### ISSUE THREAD

**Issue by wilecoyotegenius** [pnp/sp-dev-fx-property-controls#352]
#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Version
3.0.0

#### Expected / Desired Behavior / Question
ColorPicker could profit from debounce property just as SliderWithCallout did. This way it will be possible to avoid an event flooding effect when someone decides to move over palette with mouse button pressed.

#### Observed Behavior
When you try to select a color from a palette and move mouse while having mouse button pressed, component floods with onColorChanged leading to (potentially) unnecessary updates in web part.

#### Steps to Reproduce
When hovering over a color palette, click and while pressing mouse button move cursor over the palette. 

I am happy to provide a PR that adds a new property that allows introducing a delay between bubbling this.properties.onPropertyChange (in a similar fashion as in SliderWithCallout).

**Comment by joelfmrodrigues** [comment]
@wilecoyotegenius Thanks, sounds like a good improvement. As you volunteered to submit a PR with the change, will assign this issue to you
