### ISSUE TITLE
Is it normal for sppkg file to jump from 521k to 732k just by adding people picker

### ISSUE THREAD

**Issue by mikezimm** [pnp/sp-dev-fx-property-controls#353]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Version
Latest

#### Expected / Desired Behavior / Question
I installed the latest version to get the People Picker and my finished sppkg file went from 521k to 732k.
Is this normal?  I presume it is loading the entire library and not just the people picker.  Is there a way to trim down what is imported?

Question 2: If I deploy my webpart so that you need to install it on every site through Add an App, does it basically have to cache a site-specific copy of the webpart.js?  Or does it just load a cached version pointing back to the tenant app catalog?

Question 3:  If I do add this install, does it impact the gulp serve --nobrowser webpart update process?  ie make it a lot longer to see the update in the browser after I save my file in VS code?

I guess 200k is not that large when compared to images but since it is required to load before the page can be rendered, it is a little more important than images which load after.

This is all I'm using at the moment.
```typescript
import { PropertyFieldPeoplePicker, PrincipalType } from '@pnp/spfx-property-controls/lib/PropertyFieldPeoplePicker';
```

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @mikezimm - there are localization files that also included in the `.sppkg`. But they're not loaded to the page.
Could you please check if the actual `js` produced by `gulp bundle --ship` is large?

**Comment by mikezimm** [comment]
@AJIXuMuK ,
I keep backups of all the sppkg files so I just opened them up and looked at the files.  If you need me to re-do the gulp bundle --ship, let me know.

Looks like the js file Packed Size went from 366kb to 453kb.  I also did notice there were the 27 or so new localization files in there that you mentioned.

This was before:
![image](https://user-images.githubusercontent.com/49648086/116887073-df815900-abf7-11eb-81f4-0e055e7d678a.png)


This was after:
![image](https://user-images.githubusercontent.com/49648086/116887089-e314e000-abf7-11eb-9a01-1990a8326485.png)

**Comment by AJIXuMuK** [comment]
@mikezimm  - 100 Kb probably more or less expected as `PeoplePicker` uses multiple rich components from Fluent UI.
But I will take a closer look on that.

**Comment by mikezimm** [comment]
Thanks @AJIXuMuK , I think you could close this one unless you want to keep it open while you check.
I did learn a few things about how the sppkg file works (with the local strings files being loaded as needed) so that was also beneficial.

Thanks!
Mike

**Comment by joelfmrodrigues** [comment]
@mikezimm just to double-check, did you run `gulp clean` before creating the package? Seen multiple instances where people forgot to do this and their packages kept growing over time

**Comment by AJIXuMuK** [comment]
@mikezimm - I've removed 2 unused imports from the control. But I don't think it'll drastically change anything.

For your other questions.

Question 2: js files are hosted on the tenant app catalog site (or public CDN if you activated one) in any case. They're not copied/cached locally on the site collection where the app is installed.

Question 3: It should not affect the debugging.

**Comment by AJIXuMuK** [comment]
I'll close the issue. Let us know @mikezimm if you need any additional help.

**Comment by mikezimm** [comment]
@joelfmrodrigues , Yep I run gulp clean every time but thanks for the reminder.

@AJIXuMuK , Thanks for the answers to the questions!
