### ISSUE TITLE
Filter not working properly on   PropertyFieldColumnPicker

### ISSUE THREAD

**Issue by vamsi981** [pnp/sp-dev-fx-property-controls#356]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [ X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [   1.11.0  ]

Unable to add Filter through filter property Below is what it is going through browser

Filter not working properly and debugged the found the following error in the code
"SPColumnPickerService.js"

`if (this.props.filter) { if (displayHiddenColumns) queryUrl += "&$filter=&" + encodeURIComponent(this.props.filter); else queryUrl += "&$filter=Hidden eq false&" + encodeURIComponent(this.props.filter); }`

above code & should be removed other wise it will be treated as new Query string.

**Comment by joelfmrodrigues** [comment]
@vamsi981 thanks for reporting this, it does seem like a bug.
Would you be interested in trying to resolve it and submit a PR?

**Comment by AJIXuMuK** [comment]
Hi @vamsi981 - the fix has been implemented and will be included in the next release.
