### ISSUE TITLE
Stock images url is getting a 404 server error

### ISSUE THREAD

**Issue by Chrisrb05** [pnp/sp-dev-fx-property-controls#364]
#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 2.6.0 ]

#### Expected / Desired Behavior / Question

The Stock Images tab in the FilePicker control shows a 404 server error.

This issue has been resolved in the @pnp/spfx-controls-react package (Issue [#882](https://github.com/pnp/sp-dev-fx-controls-react/issues/882)) but has not been updated in the @pnp/spfx-property-controls package.

#### Observed Behavior

Network request when the Stock Images tab is loaded is attempting to load from: https://hubblecontent.osi.office.net/contentsvc/external/m365contentpicker/index.html?p=3&app=1001&aud=prod&channel=devmain&setlang=en-US&msel=0&env=prod&premium=1&themecolors=%7B%22primaryColor%22%3A%22%230078d4%22%2C%22textColor%22%3A%22undefined%22%2C%22backgroundColor%22%3A%22%23ffffff%22%2C%22neutralLighterColor%22%3A%22%23f4f4f4%22%7D and returns a 404 error. 

The request should be sent to: https://hubblecontent.osi.office.net/contentsvc/m365contentpicker/index.html?p=3&app=1001&aud=prod&channel=devmain&setlang=en-GB&msel=0&env=prod&premium=1&themecolors=%7B%22primaryColor%22%3A%22%23445068%22%2C%22textColor%22%3A%22%23333333%22%2C%22backgroundColor%22%3A%22%23ffffff%22%2C%22neutralLighterColor%22%3A%22%23f3f2f1%22%7D

#### Steps to Reproduce

Add the FilePicker control to any web part. Put the web part in edit mode, select the FilePicker control from the web part properties and select the Stock Images tab.

**Comment by ahamedfazil** [comment]
Having same issue, using following version - "@pnp/spfx-property-controls": "3.1.0" & spfx 1.12.1

Thanks,
