### ISSUE TITLE
Version 2.6 is not fully SPFx 1.12.1 compatible

### ISSUE THREAD

**Issue by IvanTheBearable** [pnp/sp-dev-fx-property-controls#366]
#### Category
- [ ] Enhancement
- [ X] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 2.6.0 and 2.7.0 beta ]

#### Expected / Desired Behavior / Question

The following code should compile:
```
PropertyFieldListPicker('propertyName', {
    label: 'Picker Label',
    onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
    properties: this.properties,
    context: this.context,
}),
```

#### Observed Behavior

Unfortunately, it fails to compile, reporting the following error on the `context: this.context,` line:

```
Type 'WebPartContext' is not assignable to type 'IWebPartContext'.
  The types of 'manifest.componentType' are incompatible between these types.
    Type 'import("/path to project/node_modules/.pnpm/@microsoft+sp-module-interfaces@1.12.1/node_modules/@microsoft/sp-module-interfaces/dist/index-internal").ComponentType' is not assignable to type 'import("/path to project/node_modules/.pnpm/@microsoft+sp-module-interfaces@1.11.0/node_modules/@microsoft/sp-module-interfaces/dist/index-internal").ComponentType'.
      Type '"AdaptiveCardExtension"' is not assignable to type 'ComponentType'.ts(2322)
IPropertyFieldListPicker.d.ts(39, 5): The expected type comes from property 'context' which is declared here on type 'IPropertyFieldListPickerProps'
```

I'm not sure how the whole dependency mechanism works but there appears to still be a dependency on 1.11.0 in there and the 2.6 controls are still using the 1.11.0 version of `IWebPartContext` which is not compatible with the 1.12.1 version of `WebPartContext`.

The lock file shows the following dependencies for @pnp/spfx-property-controls:

```
/@pnp/spfx-property-controls/2.6.0_2efcd3fc76c9f2cc9f11fc0d4a781b22:
    resolution: {integrity: sha512-s3mtN1jY0ZEgQIruH4EGb4FjqiHKMEGM84bCbcukpX8YuQ1b1VJFy6auXPb7qS2VclsTNEMq0PctRypkjlQOYw==}
    engines: {node: '>=0.10.0'}
    requiresBuild: true
    dependencies:
      '@microsoft/sp-core-library': 1.11.0
      '@microsoft/sp-lodash-subset': 1.11.0
      '@microsoft/sp-office-ui-fabric-core': 1.11.0
      '@microsoft/sp-webpart-base': 1.11.0_d8ecccf2889e06c2a80080b62409afec
      '@pnp/common': 1.3.11
      '@pnp/logging': 1.3.11
      '@pnp/odata': 1.3.11_0735193bd073e5cc36fcb4261de894d9
      '@pnp/sp': 1.3.11_97ef0e213a5999822e11d2e99b1ed457
      '@pnp/sp-clientsvc': 1.3.11_5ebb02c573206a4d27a8d882b140be71
      '@pnp/sp-taxonomy': 1.3.11_aeab9ef356b7306c5f0f03811326079a
      '@pnp/telemetry-js': 2.0.0
      '@uifabric/icons': 7.5.17_d8ecccf2889e06c2a80080b62409afec
      lodash.omit: 4.5.0
      markdown-to-jsx: 6.11.4_react@16.8.5
      office-ui-fabric-react: 6.214.0_d8ecccf2889e06c2a80080b62409afec
      react: 16.8.5
      react-ace: 5.8.0_react-dom@16.8.5+react@16.8.5
      react-dom: 16.8.5_react@16.8.5
    transitivePeerDependencies:
      - '@types/react'
      - '@types/react-dom'
    dev: false
```

#### Steps to Reproduce
Option 1. Upgrade an existing project that uses PropertyFieldListPicker. Odds are that it already contains `context: this.context`

Option 2:
1. Build a new default 'HelloWorld' web part using the 1.12.1 yo generator.
2. Add spfx-property-controls
```
npm install @pnp/spfx-property-controls@latest
```
3. Add the following to the `groupFields` array in `getPropertyPaneConfiguration` in `HelloWorldWebPart.ts`:
```
PropertyFieldListPicker('toolboxItemsList', {
    label: 'Toolbox items list',
    onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
    properties: this.properties,
    context: this.context,
})
```
4. Add the import to `HelloWorldWebPart.ts`:
```
import { PropertyFieldListPicker } from '@pnp/spfx-property-controls/lib/PropertyFieldListPicker';
```
5. Compile.

*Note:* As a workaround, changing the line to ```context: this.context as any,``` keeps the compiler happy and appears to work well enough to let me get on with other things. I don't know enough about the inner workings of SPFx to trust it in production though.

**Comment by joelfmrodrigues** [comment]
Hi @IvanTheBearable, version 2.X is for SPFx 1.11.0. For SPFx 1.12.1 you should be using version 3.1.0 of the property controls.
Please try updating to 3.1.0 as that should resolve the issue

**Comment by IvanTheBearable** [comment]
Hmm. 2.6 and 2.7 beta is all pnpm offered me. I will look into that. Thank you.

**Comment by joelfmrodrigues** [comment]
@IvanTheBearable you can see a list of all versions here: https://www.npmjs.com/package/@pnp/spfx-property-controls (click on the Versions tab).

**Comment by IvanTheBearable** [comment]
Yes, I looked there. What appears to have happened is that I didn't look past the @latest and @next tags, which are 2.6 and 2.7 beta respectively. I didn't scroll down enough to see 3.1. :-)
