### ISSUE TITLE
PropertyFieldCollectionData is not setting sortIdx on resulting collection when using Add and Save

### ISSUE THREAD

**Issue by kpfeuffer** [pnp/sp-dev-fx-property-controls#369]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [   2.7.0    ]

#### Expected / Desired Behavior / Question

The PropertyPaneFieldCollectionData with enableSoting enabled always returns a collection with the corresponding sort-position.

#### Observed Behavior

When using the PropertyFieldCollectionData with enableSoriting set to true, the corresponding sortIdx is not set when using the _Save & Add_-Button, but the value is set when saving the panel again or using the Add-Buttons on the right side.

**Comment by AJIXuMuK** [comment]
Thank you @kpfeuffer for reporting the issue!
The fix has been implemented and will be included in the next release.
