### ISSUE TITLE
Making multiselect in CustomCollectionFieldType more feasible

### ISSUE THREAD

**Issue by gallantdon** [pnp/sp-dev-fx-property-controls#378]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [3.2.0]

#### Expected / Desired Behavior / Question
Is it possible to pass the "previous" value of the selection into the onCustomRender of the custom collection field type? I am trying to implement a multiselect using a dropdown and the item itself is not available within the onChange function, meaning I cannot append to an array, even if that is my value.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @gallantdon - sorry for the long delay.
Could you explain why you need this parameter in render function?
If you have a custom control, you can have your own "state" where you can store previous value if you need it.
I don't think `prevValue` should be a parameter of `onCustomRender`

**Comment by gallantdon** [comment]
I believe the reason was that I was attempting to use the pnp control multiselect and to pass a prevValue would allow for me to use that without needing create a custom control just for managing this piece.

**Comment by AJIXuMuK** [comment]
@gallantdon - I would just use dropdown from the OUIFR for the custom implementation.
