### ISSUE TITLE
[Question] PropertyFieldCollectionData: number input shows placeholder instead of 0

### ISSUE THREAD

**Issue by M365Bass** [pnp/sp-dev-fx-property-controls#379]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Version
Please specify what version of the library you are using: [v3.2.0]

Using PropertyFieldCollectionData with a number input (CustomCollectionFieldType.number), a value of 0 seems to clear the input field's contents and show the placeholder text instead of showing 0. This is problematic when 0 is a valid input.

![Zero shows placeholder](https://user-images.githubusercontent.com/11630074/124226564-ad836900-db4c-11eb-8b8f-a950be660c75.gif)

Is this expected behaviour? If it is, would it be useful to make it configurable?

**Comment by AJIXuMuK** [comment]
Thanks @M365Bass for reporting this one and sorry for the long delay.
It is definitely a bug. 
And it has been finally fixed. Will be included in the next release.

**Comment by M365Bass** [comment]
Thanks @AJIXuMuK - appreciate your efforts 👏🏻
