### ISSUE TITLE
[ColorPicker] - Ingnoring Hue Bar

### ISSUE THREAD

**Issue by ikaroamorim** [pnp/sp-dev-fx-property-controls#380]
The property pane color picker, when we move the selector for full left or full bottom, the component stops to listen to the hue bar. If you are, for instance in blue on the hue bar, the color back to red and even if you move the picker it still red.

![image](https://user-images.githubusercontent.com/44349801/125296407-a4d52480-e2fc-11eb-9c63-5de095f0e867.png)

![image](https://user-images.githubusercontent.com/44349801/125298767-d51dc280-e2fe-11eb-8e4e-6b3eb085188e.png)

![image](https://user-images.githubusercontent.com/44349801/125298899-f8487200-e2fe-11eb-9b5b-49aff324f1ec.png)

 

#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ SPFX 1.11.0, @pnp/spfx-property-controls: 1.12.0 ]

#### Expected / Desired Behavior / Question
When you move the color to full left or full bottom keeps the hue bar as it is and don't change the color to red

#### Observed Behavior
When you move the color to full left or full bottom the hue bar is ignored  and even if move the color again it won't listen to hue.

#### Steps to Reproduce
Create a Webpart with color picker, move the  hue to any color, move the color picker to full left or full bottom, the hue bar will be ignored. The hue bar will be listened again only if changed its value (third image)

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @ikaroamorim - thank you for reporting this one and sorry for the delay.
Could you update the version of controls you're using to the latest one?
I assume there was an issue in Fluent UI that we're using under the cover.
And currently we're on v7 instead of v5 in the version you're on.
