### ISSUE TITLE
SitePicker shows App Catalog

### ISSUE THREAD

**Issue by spverma03** [pnp/sp-dev-fx-property-controls#382]
#### Category
- [ ] Question

#### Observed Behavior
Site Picker shows unwanted sites as well such as App Catalog. Is there a way to exclude/filter some sites?

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @spverma03 - sorry for the long delay.
We've introduced the new property `additionalQuery?: string;` that allows you to add an additional query to filter out sites you don't want.
