### ISSUE TITLE
Site Picker doesn't return sites with title with 2 or less characters

### ISSUE THREAD

**Issue by joaoworkhub** [pnp/sp-dev-fx-property-controls#386]
#### Category
- [x] Enhancement
- [X] Bug
- [ ] Question

#### Version
Please specify what version of the library you are using: [2.7.0]

#### Expected / Desired Behavior / Question
There are many sites with just 2 characters in the title, like TI, HR etc. I would like to find these sites typing one or two characters (maybe with component property that allow me to set minimun characters to type before run search).

#### Observed Behavior
These sites are missing in the result set when I type full title. The only way to retrive is typing multiple spaces (very strange, and not obvious for users)

#### Steps to Reproduce
1. Add PropertyFieldSitePicker to the Property Pane
2. Type search text with 2 or 1 characters
3. Sites with 2 or 1 characters on title cannot be found

**Comment by joaoworkhub** [comment]
Any updates about that issue?

**Comment by AJIXuMuK** [comment]
Hello @joaoworkhub - that is a good suggestion.
I will look into it to provide some solution.

BTW, we encourage everyone to make PRs. So, if you want to implement that feature - just let us know.

**Comment by milanholemans** [comment]
Looks like it explicitly checks if the search term is greater than 2 characters .
![afbeelding](https://user-images.githubusercontent.com/11723921/157976253-51c11a9f-dac9-4634-81f3-f52c086d65ea.png)

The search query used to search for sites also works with 2 or less characters (tested it). I can adjust this so the component searches when at least 1 character is entered.
