### ISSUE TITLE
PropertyFieldDateTimePicker: formatDate property doesn't apply to the textbox value in the property pane

### ISSUE THREAD

**Issue by m23-github** [pnp/sp-dev-fx-property-controls#388]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [2.7.0]

#### Expected / Desired Behavior / Question
When we fill the formatDate property, it should be refleted in the DatePicker textbox value in the property pane so we present the date value in the desired format.
The main goal of this enhancement is to present the date to the user while editing the webpart in the format desired because the date format is different in various cultures.

#### Observed Behavior
Textbox value is always presented in the toDateString() format, example: Thu Aug 19 2021, despite the formatDate property.

![image](https://user-images.githubusercontent.com/88783828/129042089-1fcb087b-5e01-464c-8228-76cff952cada.png)
![image](https://user-images.githubusercontent.com/88783828/129042679-1916ed7d-dce7-461f-b100-ceaa571f41a3.png)

#### Steps to Reproduce

1. Create a new webpart with the PropertyFieldDateTimePicker;
2. Fill the formatDate property with a custom format;
3. Edit the webpart and select a date;

#### Submission Guidelines
If the formatDate property is filled, pass this value to the DatePicker office fabric ui control that exists in the PropertyFieldDateTimePickerHost.tsx component.

Thanks!

**Comment by AJIXuMuK** [comment]
Thank you @m23-github for reporting this one.
The fix has been made and will be included in the next release.
