### ISSUE TITLE
FilePicker cannot find library based on its name

### ISSUE THREAD

**Issue by LennardCZ** [pnp/sp-dev-fx-property-controls#389]
#### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [    3.2.0     ]

#### Expected / Desired Behavior / Question

List all elements in a default document library

#### Observed Behavior

The Filepicker cannot find the default library based on its name if the browser language is not english (German in this case). This results in a 404 error when trying to open the 'Documents' library (because for example it is called 'Dokumente' in German)

The request call is: https://*mysharepoint*.com/sites/*exampleSite*/_api/web/lists/GetByTitle('Dokumente')/RenderListDataAsStream

#### Steps to Reproduce
Changing the language of the browser and trying to acces a Default library

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @LennardCZ - could you please provide more details?

If I change my browser language to any other - it doesn't change the title of the document library in the site. It is still Documents.
When exactly are you experiencing the issue?

**Comment by LennardCZ** [comment]
Hello @AJIXuMuK - Thank you for answering.

I have configured the FilePicker to only display the "Recent" and "Website" tabs. Accordingly I get all the Listst on the current page.

English
![filePicker_en](https://user-images.githubusercontent.com/49514884/142840636-713454af-57bf-41eb-8d13-9fb67c9da7f7.png)

German
![filePicker_de](https://user-images.githubusercontent.com/49514884/142840701-f447b6ac-f83f-4dc0-b09c-a93e36f25411.png)

As you can see, the List "BpmnLib" is displayed the same in both images, since it is a custom List I created.
The other two List, "Documents" and "Site Assets", are Lists, that are created by default when creating a SharePoint Site and are getting translated.

Upon inspecting i found out, that receiving the content of a List in the FilePicker is handled by the following POST request:

https://*mySharePoint.com*/sites/*MySite*/_api/web/lists/GetByTitle('*ListName*')/RenderListDataAsStream

The *ListName* in my cases gets replaced by the displayed Name seen in the pictures.
Accordingly the Requests are:

https://*mySharePoint.com*/sites/*MySite*/_api/web/lists/GetByTitle('Documents')/RenderListDataAsStream

for english, and 

https://*mySharePoint.com*/sites/*MySite*/_api/web/lists/GetByTitle('Dokumente')/RenderListDataAsStream

for german.

Apparently the "GetByTitle" Method does not handle the translation correctly, or the FilePicker does not know that he has to use an untranslated value to search for a List.
I also tried this with Italian and received the same behaviour

**Comment by AJIXuMuK** [comment]
Thank you @LennardCZ for the explanations.
The issue has been fixed and will be included in the next release.
