### ISSUE TITLE
Include typings for mystrings/localization

### ISSUE THREAD

**Issue by ellinge** [pnp/sp-dev-fx-property-controls#391]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version
3.2.0

#### Desired Behavior
In https://github.com/microsoft-search/pnp-modern-search/pull/1282 I found a need to use the localized required message from this library when doing custom validation. But the interface/typings/module in mystrings is not included in the bundle/output.

They are probably regarded as internal but I don’t see big impact on them being included for reuse.

**Comment by AJIXuMuK** [comment]
Hi @ellinge - why do you need strings from the library, but not creating your own set of strings?

**Comment by ellinge** [comment]
As described in the issue, instead of having to write a required message for all your already implemented languages I can only reuse it if exposing it as suggested. There's a dependent custom validation done in the pnp-modern-search issue which means a field is not required all the time.

**Comment by AJIXuMuK** [comment]
Thank you for adding the PR for that enhancement!
