### ISSUE TITLE
Improved validation and conditional support for PropertyFieldCollection

### ISSUE THREAD

**Issue by ellinge** [pnp/sp-dev-fx-property-controls#392]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version
3.2.0

#### Desired Behavior
In https://github.com/microsoft-search/pnp-modern-search/pull/1282 I found a need to add some custom validation and conditional headers which seemed to be hard to do with the out of the box exposed methods/events available in https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldCollectionData.

It would be nice to have a possibility to use onGetErrorMessage on row level or similiar to validate on multiple fields. Instead of using field label: for this output it would only add a error message with what’s returned. It also should be triggered for the boolean field type as that currently does not seem to work.

When it comes to the conditional visibility of columns one could suggest to include a visible-property on field level. This would require an event such as onRowUpdate(currentItem, items, fields) or similar though. It also could be a predicate property isVisible={items =>.

This would make it easier to create more dynamic listings that has more advanced dependencies.

**Comment by AJIXuMuK** [comment]
@ellinge - I assume this one will be fixed in the next release as we've merged all of the PRs, correct?

**Comment by ellinge** [comment]
Yes, should cover the needs for pnp search at least.
