### ISSUE TITLE
[PropertyFieldOrder] Not working with array of objects

### ISSUE THREAD

**Issue by 19ahmed99** [pnp/sp-dev-fx-property-controls#396]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Expected / Desired Behavior
The PropertyFieldOrder is not working with array of objects as described in the documentation. 

#### Observed Behavior
This error message is prompted in the console when I try to move any object using the PropertyFieldOrder:
 
![error message](https://user-images.githubusercontent.com/32335472/134653998-7687be92-6c8b-4957-8e65-859d5d091e9e.PNG)

The control does not change the ordering of the object but deletes the object I tried to move. 

#### Steps to Reproduce
I followed the  steps described in the documentation: https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldOrder

#### Temporary fix
To overcome such error temporarily, I had to wrap each object in an array which made the control work but the text property did not display as the control was not able to find the name of the property due to the wrapping. 

Thanks!

**Comment by nataliyaioffe** [comment]
I am experiencing this issue as well. Any update?

**Comment by AJIXuMuK** [comment]
Thank you @19ahmed99 for reporting this issue.
The fix has been done and will be included in the next release.

You can use beta version in a meantime.
