### ISSUE TITLE
Add a handler to close a filepicker

### ISSUE THREAD

**Issue by yarkovaleksei** [pnp/sp-dev-fx-property-controls#401]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [1.20.0]

#### Expected / Desired Behavior / Question
Hello! Is it possible to add a handler to close a filepicker without selecting a file?

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @yarkovaleksei  - could you please provide more details on your idea?
Do you need an API that can be called from outside the control to initiate closing of the panel?

**Comment by yarkovaleksei** [comment]
@AJIXuMuK No) I need a handler for clicking on the "Cancel" button when you change your mind about choosing a file.

https://github.com/pnp/sp-dev-fx-property-controls/blob/master/src/propertyFields/filePicker/PropertyFieldFilePicker.ts#L47

```typescript
private onCancel?: () => void;
// or
private onClose?: () => void;
```

**Comment by AJIXuMuK** [comment]
Gotcha @yarkovaleksei.
The improvement has been done and will be included in the next release.

**Comment by yarkovaleksei** [comment]
@AJIXuMuK Thanks a lot. And will functionality be added to version 1? It so happened that we are using the 1.20.0 package and cannot update.

**Comment by AJIXuMuK** [comment]
@yarkovaleksei - we're not actively maintaining v1 (mostly bugs).
But if you create a PR - will be happy to review and include it in v1.
