### ISSUE TITLE
Some sites do not show up in Property Field Site Picker control.

### ISSUE THREAD

**Issue by spverma03** [pnp/sp-dev-fx-property-controls#402]
#### Category
- [ ] Enhancement
- [x] Bug
- [x] Question

#### Version

3.2.0

#### Expected / Desired Behavior / Question
We are observing that not all sites are fetched by PnP Property Field Site Picker Control. Specially sites having same templates. This is related to similar bug we recently observed in PnP Site Picker Control (spfx-controls-react), which was fixed. Hopefully, a similar code will fix this issue as well.

Reference: [Issue#1026](https://github.com/pnp/sp-dev-fx-controls-react/issues/1026)

#### Observed Behavior
Some sites do not show up in Site Picker control. There is no way to search using URL as well. It becomes difficult to search and select a specific site if multiple sites have similar names/title.

#### Steps to Reproduce
Search for some site which has similar name such as "Test Site 1", "Test Site 2", "Test Site 20", Test Site 200" etc. Some sites show up but some sites will not come in site picker. Maybe because search query excludes those sites as duplicate sites.

#### Resolutions Expected
1. Important - Update the search query to include duplicate sites so that it do not exclude some sites from search results.

2. In case of PropertyFieldSitePicker control there are only 5 search results (Can we make this configurable at least or have a show more CTA). 

3. Unlike OOB control, we cannot search by URL (Good to have search by URL feature). Due to this, the control sometimes do not show the searched site in the options.

Thanks!

**Comment by spverma03** [comment]
Hi @AJIXuMuK, Adding you to this thread so that you can support in triage of this issue.

**Comment by AJIXuMuK** [comment]
Thanks @spverma03 for reporting this one!

It has been fixed and will be included in the next release.

**Comment by spverma03** [comment]
@AJIXuMuK Thank you for the update. Is there any expected timeline for next release rollout?

**Comment by AJIXuMuK** [comment]
@spverma03 - I suppose next week or a week after next
