### ISSUE TITLE
PropertyFieldCodeEditor width

### ISSUE THREAD

**Issue by RasheshJagad** [pnp/sp-dev-fx-property-controls#404]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 3.2.0 ]

#### Expected / Desired Behavior / Question
If we can specify the width of the PropertyFieldCodeEditor that will really help if we have more things to be written.

#### Observed Behavior
The width of the PropertyFieldCodeEditor is not modifiable.

#### Steps to Reproduce
General steps

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @RasheshJagad - thank you for the suggestion.
The change has been made and will be included in the next release.

**Comment by RasheshJagad** [comment]
Thanks for taking this into considering and updating Team.

**Comment by pwmusic** [comment]
I can see there is now the facility to include a panelWidth property, but it doesn't seem to have any effect.

I've tried:
`
options: {
    panelWidth: 80,
}
`

and
`
properties: { panelWidth: 80 },
`

Whether I set the width to 80 or 8, the panel width doesn't change.

Hopefully it's something I've got wrong in my code but please let me know if there's anything else I can do to help track down this issue.

"@pnp/spfx-property-controls": "^3.14.0",
SharePointOnline
