### ISSUE TITLE
Incompatible with SPFx 1.13

### ISSUE THREAD

**Issue by thechriskent** [pnp/sp-dev-fx-property-controls#405]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 3.2 ]

#### Expected / Desired Behavior / Question
Using the PropertyFieldListPicker should work

#### Observed Behavior
Unable to configure it because I receive the following error when setting context to `this.context` (SPFx Webpart):

```
 Type 'WebPartContext' is not assignable to type 'BaseComponentContext'.
  Types have separate declarations of a private property '_serviceScope'.ts(2322)
```

#### Steps to Reproduce
Create an SPFx 1.13 webpart, add the property controls, attempt to configure the PropertyFieldListPicker

**Comment by AJIXuMuK** [comment]
Hi @thechriskent - thanks for reporting this one.
1.13.* support will be included in the next release.

**Comment by AJIXuMuK** [comment]
it is released.

**Comment by sortegamartin** [comment]
Hi, I see that the latest release is v3.2.0 generated on June 23.  When will the release that includes these latest changes be released?

**Comment by AJIXuMuK** [comment]
Sorry - there is some issue with the pipeline. It should have been released last week.
Will check out what's going on and release it correctly.

**Comment by AJIXuMuK** [comment]
3.3.0 has been release.

Should be good now.
