### ISSUE TITLE
PropertyPaneDateTimePicker does not display correctly when deployed

### ISSUE THREAD

**Issue by rheajt** [pnp/sp-dev-fx-property-controls#409]
#### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 3.2 ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
When I added the DateTimePicker it works fine as described in documention. When I bundle and ship to my tenant, the date picker becomes only partially visible in the property pane.

![image](https://user-images.githubusercontent.com/11312561/142976552-ad02b14e-53f5-4948-8f29-d4121f4c5ada.png)

#### Steps to Reproduce
I installed as described in the docs. Everything looked fine in local development and tenant workbench. When bundled/shipped it gets cut off.

Thanks!

**Comment by AJIXuMuK** [comment]
Hello @rheajt. Thank you for reporting this one.
Just for clearance - are you using isolated web part?

**Comment by rheajt** [comment]
@AJIXuMuK  Yes (I think so). It is basically boilerplate directly from the generator and the property pane stuff installed.

**Comment by AJIXuMuK** [comment]
@rheajt - unfortunately, it is by design.
We are limited with what's provided by SPFx and Fluent UI.
In that case isolated web part's property pane is rendered in an iframe with limited width.
This width is not enough to display Fluent UI `DatePicker`.
And there is no property to display it inline.
