### ISSUE TITLE
PropertyFieldFilePicker should allow setting a default tab

### ISSUE THREAD

**Issue by chrisfriz** [pnp/sp-dev-fx-property-controls#412]
#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [3.2.0]

#### Expected / Desired Behavior / Question
PropertyFieldFilePicker should allow to be configured optionally with a default tab, instead of defaulting to the recent tab, since this doesn't make sense if the recent tab is hidden. Happy to contribute with a PR for the changes.

**Comment by AJIXuMuK** [comment]
Thank you @chrisfriz for the suggestion, and for sure feel free to create a PR!

Thanks!

**Comment by MaazKhanaa** [comment]
i want to add a default value for PropertyFieldFilePicker in property pane but its not working please give me the solution
