### ISSUE TITLE
Evaluates as false on valid values like "", 0, false

### ISSUE THREAD

**Issue by michaelcoxon** [pnp/sp-dev-fx-property-controls#416]
https://github.com/pnp/sp-dev-fx-property-controls/blob/dd2f4eff1ace10ce5ae19c72f1911a6b7355ef31/src/propertyFields/propertyEditor/PropertyPanePropertyEditorHost.tsx#L50

**Comment by AJIXuMuK** [comment]
Thank you @michaelcoxon for reporting this one.
The issue has been fixed in 3.3.0
