### ISSUE TITLE
PropertyFieldChoiceGroupWithCallout: iconProps not working

### ISSUE THREAD

**Issue by pk-1990** [pnp/sp-dev-fx-property-controls#424]
#### Category
Bug

#### Version

Please specify what version of the library you are using: [    3.3.0     ]

#### Expected / Desired Behavior / Question
When using the PropertyFieldChoiceGroupWithCallout, specifying the iconProps property in combination with the officeFabricIconFontName should render choice buttons with an icon instead of a regular radio button, just like the OOTB PropertyPaneChoiceGroup

#### Observed Behavior
When using the iconProps as below, the choice group does render buttons instead of radio buttons, but the icon is missing, leaving empty choice buttons instead :

{
    key: 'Option1',
    text: 'Option #1',
    iconProps: {
        officeFabricIconFontName: 'BulletedList2'
    }
},

#### Steps to Reproduce
Use the PropertyFieldChoiceGroupWithCallout control and specify an option using the code below, and notice the icon missing :

{
    key: 'Option1',
    text: 'Option #1',
    iconProps: {
        officeFabricIconFontName: 'BulletedList2'
    }
}, 

This issue is similar to [Issue 154](https://github.com/pnp/sp-dev-fx-property-controls/issues/154). However it is not working with the latest version.

Thanks!

**Comment by AJIXuMuK** [comment]
Thank you @pk-1990 for reporting this issue!
It has been fixed and the fix will be included in the next release.
