### ISSUE TITLE
@pnp/spfx-property-controls PropertyFieldFilePicker => Upload does not work and Site Assets does not show files for other languages

### ISSUE THREAD

**Issue by BorisLand** [pnp/sp-dev-fx-property-controls#425]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Version
"@pnp/spfx-property-controls": "3.3.0"

### Component
PropertyFieldFilePicker

#### Expected
1. Upload File work fine
2. Library "Site Assets" display all file for other language (example: german)

#### Observed Behavior
1. Upload file does not work. No file Uploaded.
2. Switch the browser language to german, select "Website" (german; english = "Site") and open the library "Websiteobjekte" (german; englisch = "Site Assets"). The Folder show "Dieser Ordner ist leer" (german: english = "This folder is empty").
In english this works without any problems

#### Steps to Reproduce
1. Create new SPFx webpart project using yeoman
2. 
npm i @pnp/spfx-controls-react
npm i @pnp/spfx-property-controls

Package.json
"dependencies": {
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "office-ui-fabric-react": "7.174.1",
    "@microsoft/sp-core-library": "1.13.0",
    "@microsoft/sp-property-pane": "1.13.0",
    "@microsoft/sp-webpart-base": "1.13.0",
    "@microsoft/sp-lodash-subset": "1.13.0",
    "@microsoft/sp-office-ui-fabric-core": "1.13.0",
    "@pnp/spfx-controls-react": "3.5.0",
    "@pnp/spfx-property-controls": "3.3.0"
  }

3. add import an ...webpart.ts
import { PropertyFieldFilePicker, IPropertyFieldFilePickerProps, IFilePickerResult } from "@pnp/spfx-property-controls/lib/PropertyFieldFilePicker";

4. add property pane configuration
PropertyFieldFilePicker('filePicker', {
                  context: this.context as any,
                  filePickerResult: this.properties.filePickerResult,
                  onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
                  properties: this.properties,
                  onSave: (e: IFilePickerResult) => { 
                    console.log(e); 
                    this.properties.filePickerResult = e;  
                  },
                  onChanged: (e: IFilePickerResult) => { 
                    console.log(e); 
                    this.properties.filePickerResult = e; 
                  },
                  key: "filePickerId",
                  buttonLabel: "File Picker",
                  label: "File Picker",
              })

4. change webpart props

export interface IHelloWorldWebPartProps {
  filePickerResult: IFilePickerResult;
}

5. gulp serve

**Comment by SPFxAppDev** [comment]
I also have this problem with multilingualism. In the FilePicker control (from @pnp/spfx-controls-react) the items are fetched from the list via the URL, in the PropertyFieldFilePicker Control still via the list title. And if it's a title from another language than the default web language, the call doesn't work. I think, it is the getListItems-Method in the [FileBrowserService](https://github.com/pnp/sp-dev-fx-property-controls/blob/master/src/services/FileBrowserService.ts)

**Comment by AJIXuMuK** [comment]
@BorisLand @SPFxAppDev I made changes for multilingual support while fixing #389. The fixes are available in beta version.
Could you please check if this issue has been resolved as well?

**Comment by SPFxAppDev** [comment]
@AJIXuMuK Looks good. I now get the files for other languages as well. Thanks

**Comment by AJIXuMuK** [comment]
Thanks for the confirmation!
