### ISSUE TITLE
Unable to use some property controls in ACEs

### ISSUE THREAD

**Issue by anoopt** [pnp/sp-dev-fx-property-controls#431]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
Please specify what version of the library you are using: [3.4.0]

#### Cause of the issue
Some of the PnP SPFx property controls are importing `IPropertyPaneField` , `PropertyPaneFieldType` and other data from `@microsoft/sp-webpart-base` instead of `@microsoft/sp-property-pane`. 

![image](https://user-images.githubusercontent.com/9694225/153862369-db30500e-d9e7-4558-b0fa-2778637d1d4a.png)

#### Expected / Desired Behavior / Question
Property pane controls should be usable in ACEs like we use them in SPFx web parts.

#### Observed Behavior
When some property pane controls are added to ACEs an error is seen when we run `gulp serve` and hence when we edit the ACE the property pane doesn't load. 

#### Steps to Reproduce
1. Create an SPFx ACE
2. In the property pane add a PnP SPFx property control (e.g. `PropertyFieldCollectionData` or `PropertyFieldGuid`)
3. Save and run `gulp serve`
4. See errors in the terminal window

**Comment by joelfmrodrigues** [comment]
@anoopt many thanks for raising this issue and providing detailed information.
This is now fixed and will be available as part of the next major release.
It will also be available in the beta release that should be published within the next few minutes.

**Comment by anoopt** [comment]
Thank you @joelfmrodrigues
