### ISSUE TITLE
PropertyFieldCollectionData add button disabled when it should not be

### ISSUE THREAD

**Issue by c-eiser13** [pnp/sp-dev-fx-property-controls#436]
#### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [    3.4.0     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Observed Behavior
When using the PropertyFieldCollectionData control with non-required fields, when I have entered no data yet, the plus icon is active and I can add additional rows.
![_bug_1](https://user-images.githubusercontent.com/42096464/156416974-b2759d43-17f4-4a04-8212-e3ec2ce0cdc7.png)
![_bug_2](https://user-images.githubusercontent.com/42096464/156416985-73614311-663b-4839-836f-a3d9d1d1765c.png)

However, as soon as I begin typing in the first field, the plus button becomes disabled
![_bug_3](https://user-images.githubusercontent.com/42096464/156417045-75ad0592-76cc-429b-b3be-5871eb740626.png)

If I continue to fill out all fields, the plus button stays disabled, unless I remove all data from all fields. 
![_bug_4](https://user-images.githubusercontent.com/42096464/156417221-9afea0c5-45ce-4b36-8142-d486da27a83f.png)

The component is configured as follows:
![image](https://user-images.githubusercontent.com/42096464/156417582-a63e1bcf-a38c-4914-a036-f4041d2511c2.png)

At this point, I can only enter 1 row, click add/save, then re-open panel to add a second, third, etc row. For sake of entering issue, I made all fields non-required, but my solution requires the first 2 where the last one is optional. In this scenario, the plus is active until I enter the two required fields, then it disables.

#### Steps to Reproduce
Add a PropertyFieldCollectionData to web part and configure as described above, then enter data and try and use the plus to add a new row.

**Comment by c-eiser13** [comment]
Found and debugged the issue and will be submitting a pull request with potential fix.

**Comment by joelfmrodrigues** [comment]
@c-eiser13 that's great! Many thanks! I will assign this item to you just to avoid other people seeing it as start work on it
