### ISSUE TITLE
PropertyFieldCollectionData onUpdate does not cause Add/Add and save button to be enabled

### ISSUE THREAD

**Issue by IRRDC** [pnp/sp-dev-fx-property-controls#446]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [3.6.0]

#### Expected / Desired Behavior / Question
When a custom field rendering field is required and a value gets selected or entered the Add and the Add and save buttons need to be enabled if there are no other required fields.

#### Observed Behavior
When using custom field rendering for the only required field and calling onUpdate with a changed value this will not trigger the check that en/disables the Add and the Add and save buttons. One of the fields of a built-in field type needs to be changed for the buttons to update.

**Comment by IRRDC** [comment]
I just noticed another problem in this scenario: Changes to existing data rows won't get saved.

**Comment by ivonool** [comment]
> I just noticed another problem in this scenario: Changes to existing data rows won't get saved.

I can confirm this, ran to this issue also.

**Comment by mariuszwojtkowski** [comment]
The fix looks good - pls merge asap!

**Comment by xavisegura** [comment]
Same here, the fix looks good, please merge.

**Comment by AJIXuMuK** [comment]
The fix has been merged.
It is available in beta version and will be included in the next release.
