### ISSUE TITLE
Enhancement: provide preview of the current selected color for PropertyFieldColorPicker component.

### ISSUE THREAD

**Issue by milanholemans** [pnp/sp-dev-fx-property-controls#447]
#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Version
Please specify what version of the library you are using: [ 3.6.0 ]

#### Expected / Desired Behavior / Question
For the `PropertyFieldColorPicker` component, provide the ability to see the current selected color.

#### Observed Behavior
Currently impossible to get a preview of the current selected color.

#### Steps to Reproduce
Add the PropertyFieldColorPicker component.

**Comment by AJIXuMuK** [comment]
Thank you @milanholemans for proposing the enhancement and implementing it!
