### ISSUE TITLE
Any way to update the styling of the rendered PropertyFieldTermPicker component? 

### ISSUE THREAD

**Issue by RPWPA** [pnp/sp-dev-fx-property-controls#460]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [    3.6.0     ]

#### Expected / Desired Behavior / Question
Is there a way to be able to change the rendering of the "PropertyFieldTermPicker"?  
I tried creating my HTMLElement and using it on the OnRender() method but nothing changed. 
I'm asking because I need to be able to change the text color as I need to handle how the termsets look depending on the current theme of the site. 

Many Thanks!

**Comment by AJIXuMuK** [comment]
@RPWPA - we are not setting any colors directly, so theoretically it should use the styles from the theme automatically.
Could you please describe what parts of the component has issues?
Thanks!
