### ISSUE TITLE
Arabic local missing for resource "PropertyControlStrings"

### ISSUE THREAD

**Issue by JeanNetryValere** [pnp/sp-dev-fx-property-controls#461]
Hello, 

it appears that the localization data is missing for Arabic language. Is this possible to have or plan it in next release please ?

#### Category
- [x] Enhancement
- [x] Bug
- [ ] Question

#### Version
version of the library: [3.6.0]

#### Expected / Desired Behavior / Question
ar-sa.js shipped in package -> dist folder

#### Observed Behavior
Error - [webpack] 'dist':
The selected locale (ar-sa) is not present in the localized data for resource "PropertyControlStrings".

#### Steps to Reproduce
In the built solution the src/loc/ar-sa.js ressource file is present
then 
gulp serve --locale=ar-sa

Thanks!

**Comment by JeanNetryValere** [comment]
Hello @milanholemans,
It is pushed. Let me know if additional steps are required.
Bye

**Comment by milanholemans** [comment]
Hi @JeanNetryValere, looks good!
Now we have to wait for this PR to be reviewed and completed. ☺️
