### ISSUE TITLE
Extend ICustomCollectionField with disable option

### ISSUE THREAD

**Issue by Jwaegebaert** [pnp/sp-dev-fx-property-controls#464]
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ latest ]

####  Question

When you want to disable a field in the control `CollectionData`, you have to pass the option `disableEdit: true`. This forces all the fields in a column to be disabled after creation. Here it would be nice to have the option to conditionally disable a field.  For example, when a users unticks a toggle field that the next field becomes disabled.

![afbeelding](https://user-images.githubusercontent.com/38426621/174056109-1a398af9-69f8-4788-927c-861ae80cdf81.png)

####  Implementation

This could be achieved by adding a new function to the interface `ICustomCollectionField` that looks a bit like the following.

``` javascript
/**
 * Conditionally disable a field
 */
disable?: (item: any) => boolean;
```

Then we can pass this along our field options and apply a conditionally disable.

``` javascript
fields: [
  {
    id: "Sign",
    title: "Signed",
    type: CustomCollectionFieldType.boolean,
    defaultValue: true
  },
  {
    id: "IconName",
    title: "Icon Name",
    type: CustomCollectionFieldType.fabricIcon,
    placeholder: "Enter the name of the icon",
    defaultValue: "website",
    onGetErrorMessage: this.minLengthValidation,
    disable: (item) => !item.Sign
  }
]
```

**Comment by Jwaegebaert** [comment]
If everyone agrees that this could be a nice enhancement, then I can take it up. 😄

**Comment by joelfmrodrigues** [comment]
@Jwaegebaert  it would be a great improvement! And the approach is super neat 👏 
Please go ahead and submit a PR 🙂
