### ISSUE TITLE
PropertyFieldCollectionData checks custom error messages for fields that are not required

### ISSUE THREAD

**Issue by IRRDC** [pnp/sp-dev-fx-property-controls#469]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [3.6.0]

#### Expected / Desired Behavior / Question
If a field has not been set to required onGetErrorMessage should not be called. When a former required field is no longer required it should be enough to set required to false and not also be necessary to remove the onGetErrorMessage setting.

#### Observed Behavior
I minor issue i noticed while browsing the code to find a fix for https://github.com/pnp/sp-dev-fx-property-controls/issues/446: In CollectionDataItem.tsx checkRowIsValidForSave calls checkAnyFieldCustomErrorMessage to verify that all inputs are valid. checkAnyFieldCustomErrorMessage does not check if the fields are required it just checks the error messages for all fields which results in unexpected behavior (rows not valid even when all required fields have been filled).

**Comment by AJIXuMuK** [comment]
@IRRDC - could you please describe what to your mind is invalid?
We're checking fields for validity, no matter if they're required or no.
If the field contains incorrect data - the row should not be saved.

**Comment by IRRDC** [comment]
Well, seems I was only thinking of onGetErrorMessage in terms of checking for required fields having a value not of checking the content of value for other issues.
