### ISSUE TITLE
PropertyFieldTermPicker v3.8.0 with SPFx 1.15 not loading

### ISSUE THREAD

**Issue by jacob-tornqvist** [pnp/sp-dev-fx-property-controls#481]
#### Category
- [ ] Enhancement
- [ ] Bug
- [**X**] Question

#### Version
SPfx 1.15 
Node version v14.18
@pnp/spfx-property-controls: 3.8.0

#### Expected / Desired Behavior / Question
Hi! Trying to use the PropertyFieldTermPicker, but i fail when trying to serve the web part. Recieving the following error message:

**Web part  was not initialized properly. Web parts must be instantiated using the ClientSideWebPartManager. Many web part features cannot be used till the initialization is complete.**

The context property of the control complains: Type 'WebPartContext' is not assignable to type 'BaseComponentContext'.
  Types have separate declarations of a private property '_serviceScope'.

Did try to set the context as any with no success. 

Does the latest version of @pnp/spfx-property-controls work with SPFx 1.15?

Thanks!

**Comment by Jwaegebaert** [comment]
Hey @jacob-tornqvist, could you show a code example of how you implemented the `PropertyFieldTermPicker` within your solution?

**Comment by AJIXuMuK** [comment]
@jacob-tornqvist - sorry for the late reply.
Is it still an issue for you with the latest version of the library?

Could you show a code where you initialize the component?
