### ISSUE TITLE
npm WARN ERESOLVE overriding peer dependency

### ISSUE THREAD

**Issue by trillian74** [pnp/sp-dev-fx-property-controls#517]
#### Category
- [ ] Enhancement
- [ x] Bug
- [ x] Question

#### Version

Please specify what version of the library you are using: [  3.11.0, spfx 1.15.2, node 16.15.1  ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I was expecting it to not have internal package conflict, but i haven't found any similar reports - so i hope that it is just me

#### Observed Behavior
during npm install i get these warnings.

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: adaptivecards-designer@2.3.0
npm WARN Found: monaco-editor@0.32.1
npm WARN node_modules/monaco-editor
npm WARN   monaco-editor@"^0.32.1" from @pnp/spfx-controls-react@3.11.0
npm WARN   node_modules/@pnp/spfx-controls-react
npm WARN     @pnp/spfx-controls-react@"3.11.0" from the root project
npm WARN   2 more (@pnp/spfx-property-controls, @monaco-editor/loader)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer monaco-editor@"^0.20.0" from adaptivecards-designer@2.3.0
npm WARN node_modules/@pnp/spfx-controls-react/node_modules/adaptivecards-designer
npm WARN   adaptivecards-designer@"2.3.0" from @pnp/spfx-controls-react@3.11.0
npm WARN   node_modules/@pnp/spfx-controls-react
npm WARN
npm WARN Conflicting peer dependency: monaco-editor@0.20.0
npm WARN node_modules/monaco-editor
npm WARN   peer monaco-editor@"^0.20.0" from adaptivecards-designer@2.3.0
npm WARN   node_modules/@pnp/spfx-controls-react/node_modules/adaptivecards-designer
npm WARN     adaptivecards-designer@"2.3.0" from @pnp/spfx-controls-react@3.11.0
npm WARN     node_modules/@pnp/spfx-controls-react

**Comment by Dangerous-Mind** [comment]
Any workaround?

**Comment by joelfmrodrigues** [comment]
@trillian74 this should now be resolved. Could you please confirm with the latest release?
