### ISSUE TITLE
PropertyFieldFilePicker - Site Tab - Does not scroll if many libraries

### ISSUE THREAD

**Issue by krainer** [pnp/sp-dev-fx-property-controls#525]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [ ] Enhancement
- [ X ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [latest]

#### Expected / Desired Behavior / Question

Component: PropertyFieldFilePicker

When a site contains a large number of document libraries, and the "Site" tab is selected, is is expected that the end user cal scroll through all document libraries and select the required one

#### Observed Behavior
When a site contains a large number of document libraries, and the "Site" tab is selected, then the screen will not scroll and thereby not show all items

#### Steps to Reproduce
1. Create 20-25 document libraries (empty libraries are fine) in a site collection
2. Deploy the "propertyControlsTest" web part in the site collection (ur use gulp serve)
3. Open the web part properties
4. Select "File Picker" below the "People, Terms, Files, Role Definition" headline
5. Select the "Site" tab
6. If all document libraries are shown, resize the window so it is smaller
7. The last document libraries are not available to selected

I will submit a PR with a fix

**Comment by joelfmrodrigues** [comment]
@krainer this has now been merged. Would you be interested in sending a PR with the same fix to the other repository with the reusable controls?

**Comment by joelfmrodrigues** [comment]
@krainer many thanks! Hopefully should be the same code changes
