### ISSUE TITLE
Missing Czech localization

### ISSUE THREAD

**Issue by MartinZamazal** [pnp/sp-dev-fx-property-controls#527]
Hello,
there is no Czech localization in the current version. Is it possible to iclude it? I have translated cs-cz.js file, so I can provide it.

#### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [ 3.11.0 ]

#### Expected / Desired Behavior / Question
Localized cs-cz.js file included in the next version.

#### Observed Behavior
No localized cs-cz.js file included in the current version.

#### Steps to Reproduce
No localized cs-cz.js file included in the current version.

Thanks!

**Comment by joelfmrodrigues** [comment]
@MartinZamazal not really sure why this is happening, I thought we had Czech localization and not sure how/when it was removed but surely by mistake if that was the case.
If you could send a PR that would be very helpful

**Comment by MartinZamazal** [comment]
@joelfmrodrigues PR sent. Please let me know if there is something else I can do.
