### ISSUE TITLE
Dropdown/ComboBox options not rendering inside PropertyFieldCollectionData

### ISSUE THREAD

**Issue by rzempo** [pnp/sp-dev-fx-property-controls#534]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
Please specify what version of the library you are using: [3.11.0]

#### Expected / Desired Behavior / Question
Use a Dropdown/ComboBox as a custom field inside the PropertyFieldCollectionData and the options rendering correctly. 

#### Observed Behavior
I am using PropertyFieldCollectionData with multiple custom fields, one of them being a Dropdown from @fluentui/react ^8.97.2. It used to work well when I was using @pnp/spfx-property-controls 3.2.0. I upgraded to 3.11.0 and now that dropdown doesn't render the options. It works if I use a different control. I.e., ChoiceGroup. Also, the dropdown/combobox works when used outside the PropertyFieldCollectionData. I.e., inside the web part .tsx file.

The PropertyFieldCollectionData has three custom fields: 1) select a site (SitePicker from @pnp/spfx-controls-react) 2) select a list from selected site (ListPicker from @pnp/spfx-controls-react) 3) Custom dropdown that renders the views from the selected list

#### Steps to Reproduce
Create a SPFx solution (1.16.1)
Install:
@pnp/spfx-controls-react
@pnp/spfx-property-controls-react
@fluentui/react 
@pnp/sp @pnp/graph

Add PropertyFieldCollectionData with a custom field that renders a Dropdown or ComboBox with options

Soltuion available at this OneDrive location: [https://1drv.ms/u/s!AuKiPyP7yCDrgP8U1s69ZYL08aKYiw?e=62nzC5](https://1drv.ms/u/s!AuKiPyP7yCDrgP8U1s69ZYL08aKYiw?e=62nzC5)

![image](https://user-images.githubusercontent.com/20348540/216809999-8e437c8a-4efb-4d04-8d05-19b187057b28.png)

Thanks!

**Comment by AJIXuMuK** [comment]
@rzempo - the library is still based on Fluent UI v7 (same for SPFx).
We can't guarantee v8 components will work
