### ISSUE TITLE
Does PropertyFieldColorPicker support multiple locale on SPO site?

### ISSUE THREAD

**Issue by AkiraSPO** [pnp/sp-dev-fx-property-controls#535]
**Question**:
I am trying to use PropertyFieldColorPicker control in SPFX app used in a SharePoint Online site that supports both EN and FR locale. Is there a way I can change the locale in the control so that it displays the color names (Red, Green, Blue) in French when the SPFX code is set to use FR-FR locale?

Thank you!

![image](https://user-images.githubusercontent.com/102831180/217907641-b7cbef85-0484-4a3b-893d-e5edf1e68d9c.png)

**Comment by AJIXuMuK** [comment]
@AkiraSPO - good catch!
The fix has been done and will be included in the next release!

**Comment by AkiraSPO** [comment]
Hey @AJIXuMuK - I took the latest code from the repository and observed that the color picker is showing localized color names when the picker display style is _PropertyFieldColorPickerStyle.Inline_ but the color names appear in English when the picker style is _PropertyFieldColorPickerStyle.Full_. Perhaps the property 
_strings={strings.ColorPickerStrings as IColorPickerStrings}_  also needs to be added in the <ColorPicker/> under _this.props.style === PropertyFieldColorPickerStyle.Full_
Could you please take a look? Should I open a new issue for this?
