### ISSUE TITLE
PropertyFieldDateTimePicker control: Italian localization not corrected

### ISSUE THREAD

**Issue by Luca3082** [pnp/sp-dev-fx-property-controls#547]
#### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question

#### Version

Latest

#### Expected / Desired Behavior / Question
The panel need to show correct name of week days and months

#### Observed Behavior

![image](https://user-images.githubusercontent.com/15248198/222750483-58f8374e-c47d-427a-8240-efe2005992ac.png)
Sunday is Domenica, not Sun
Monday is Lunedì, not Mio
March is Marzo, not Guastare
Some months are written in a compressed form
September is Settembre, not Sette

The localization is not corrected

#### Steps to Reproduce
- create a new react webpart with the command: yo @microsoft/SharePoint
- install the library: npm install @pnp/spfx-property-controls --save --save-exact
- in the webpart, added the component like this:
import { PropertyFieldDateTimePicker, DateConvention, TimeConvention } from '@pnp/spfx-property-controls/lib/PropertyFieldDateTimePicker';
import { IDateTimeFieldValue } from "@pnp/spfx-property-controls/lib/PropertyFieldDateTimePicker";

...

PropertyFieldDateTimePicker('wpActivationDate', {
                  label: strings.WpActivationDateFieldName,
                  initialDate: this.properties.wpActivationDate,
                  dateConvention: DateConvention.DateTime,
                  timeConvention: TimeConvention.Hours24,
                  onPropertyChange: this.onPropertyPaneFieldChanged,
                  properties: this.properties,
                  onGetErrorMessage: null,
                  deferredValidationTime: 0,
                  key: 'dateTimeFieldId',
                  showLabels: false
                })

Thanks!

**Comment by AJIXuMuK** [comment]
@Luca3082 - would you mind create a PR with the correct values for the localization?
We use Azure to translate to different languages. 
But it is not ideal.

Would be nice to have the changes from the native speaker!

**Comment by joelfmrodrigues** [comment]
Thanks @Luca3082 , PR merged
