### ISSUE TITLE
Question on timing 3.13.0

### ISSUE THREAD

**Issue by NoralK** [pnp/sp-dev-fx-property-controls#565]
Greeting,

When will v3.13.0 be available on NPM?

Cheers

**Comment by joelfmrodrigues** [comment]
@NoralK thanks for raising this issue. There was an error in the release pipeline that we are investigating and the new version should become available as soon as we fix the issue.

**Comment by NoralK** [comment]
@joelfmrodrigues Thank you for the update

**Comment by joelfmrodrigues** [comment]
@NoralK Alex was able to resolve the issue and 3.13.0 is now published 
https://www.npmjs.com/package/@pnp/spfx-property-controls

Closing this issue. Many thanks for bringing this to our attention

**Comment by NoralK** [comment]
Thank you @joelfmrodrigues I have been able to add this version
