### ISSUE TITLE
PropertyFieldChoiceGroupWithCallout deletes properties

### ISSUE THREAD

**Issue by IRRDC** [pnp/sp-dev-fx-property-controls#592]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [3.15.0]

#### Expected / Desired Behavior / Question
In the newest version the property assigned to the PropertyFieldChoiceGroupWithCallout gets deleted when a selection gets checked. 

#### Observed Behavior
The current value does not get selected on load (anymore). It does show up when looking at it using the PropertyPanePropertyEditor.
As soon as one of the options gets checked the whole property vanishes from the PropertyPanePropertyEditor.

#### Steps to Reproduce
I created a fresh SPFX webpart using yo and just added the sample codes from
https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyPanePropertyEditor/
and
https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldChoiceGroupWithCallout/
I also added "choiceGroupWithCalloutValue": "Android" to the manifest.json to create a default value.

Sample code:
![s1](https://github.com/pnp/sp-dev-fx-property-controls/assets/11270504/25918c7d-f52b-4ef4-a9e1-6aa0f3f0ecca)

No choice selected on load:
![s2](https://github.com/pnp/sp-dev-fx-property-controls/assets/11270504/fe78088b-beb6-41f9-a057-3f2d4efca2ac)

Property exists before making a choice:
![s2a](https://github.com/pnp/sp-dev-fx-property-controls/assets/11270504/d032f523-e2d9-4f68-aa46-51fc17acb6e5)

Property is gone after making a choice:
![s3](https://github.com/pnp/sp-dev-fx-property-controls/assets/11270504/97ddb47a-ff54-4725-b684-ad7611679dbb)

**Comment by IRRDC** [comment]
Also happens in the PropertyControlsTestWebPart from this repository.

**Comment by IRRDC** [comment]
One of the reasons for the bug is this change:
https://github.com/pnp/sp-dev-fx-property-controls/commit/46edef633bf6f5c628b96c1c3d44933c85be6987#diff-162be79c6bc5b46836132ba0090fc8c213f7d20933388840100ba07b547164d9
where _onChanged gets assigend to onChange which comes with 2 parameters instead of one, so changing the signature of _onChanged to include the parameter will store the result again. Strangely that doesn't fix the problem of displaying the selected choice on re-rendering yet.
```
    private _onChanged(ev?: React.FormEvent<HTMLElement | HTMLInputElement>, option?: IChoiceGroupOption): void {
        if (this._onChangeCallback) {
            this._onChangeCallback(this.targetProperty, option.key);
        }
    }
```

**Comment by IRRDC** [comment]
Does an error of this severity warrant a 3.15.1 release since it renders the PropertyFieldChoiceGroupWithCallout control unusable and may destroy existing web part configurations?

**Comment by spplante** [comment]
Noticed the same issue today, rolling back in version fixed it for now
