### ISSUE TITLE
Any plans to upgrade SPFx project version to 1.19.0?

### ISSUE THREAD

**Issue by vishalshitole** [pnp/sp-dev-fx-property-controls#624]
#### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question

#### Version

`v3.17.1`

#### Question
@AJIXuMuK Do we have any plans to upgrade the SPFx version for this project to 1.19.0? I see that we have it for *sp-dev-fx-controls-react* per your comment here - https://github.com/pnp/sp-dev-fx-controls-react/issues/1846#issuecomment-2262945142.

#### Observed Behavior
Currently it is on SPFx version 1.18.2

Thanks!

**Comment by timdhahn** [comment]
@AJIXuMuK  - Tested out the 'dev' branch with spfx 1.19 updates & the build is working. Thanks!
