### ISSUE TITLE
PropertyFieldColorPicker Palette Icon alignment Issue

### ISSUE THREAD

**Issue by sprider** [pnp/sp-dev-fx-property-controls#63]
#### Category
- [ ] Bug

#### Version
1.6.0 

#### Browser
All major 

#### Expected 
Fix the alignment issue  

#### Observed Behavior
The color palette icon is moving towards right on SharePoint pages with webpart zone but the same works as expected in workbench when we debug

**Workbench page output** 
![with workbench page](https://user-images.githubusercontent.com/21008316/39894915-0843b0fc-546e-11e8-86a4-fdaa7897ce27.gif)

**Sharepoint page output** 
![with sharepoint page](https://user-images.githubusercontent.com/21008316/39894933-15af2e7e-546e-11e8-978a-fa4afec3d7b5.gif)
Note: I do not have any other customization or webparts in this page

#### Steps to Reproduce
1. Create a SPFx webpart
2. Install sp-dev-fx-property-controls package as mentioned in https://sharepoint.github.io/sp-dev-fx-property-controls/
3. Add PropertyFieldColorPicker property  
4. Execute the app using gulp serve
5. Open the local workbench page in browser and add the app 
6. Edit the PropertyFieldColorPicker property
7. Notice the icon alignment issue  
8. Package the app the check the same from a Sharepoint page with webpart zones. 

Thanks!

**Comment by sprider** [comment]
@estruyf Can you reproduce this issue? If so, can we do something to fix this issue temporarily?

**Comment by AJIXuMuK** [comment]
Please, create a new issues if the bug is still present.
