### ISSUE TITLE
German localization

### ISSUE THREAD

**Issue by estruyf** [pnp/sp-dev-fx-property-controls#83]
#### Category
[x] Enhancement
[ ] Bug
[ ] Question

Add German localization labels

**Comment by mmsharepoint** [comment]
Can Takeover this soon if appreciated how I did it for the SPFx React controls:
https://github.com/SharePoint/sp-dev-fx-controls-react/issues/101

**Comment by AJIXuMuK** [comment]
German translation has been auto-generated using Azure cognitive services.
Please, feel free to update it if needed.

The translation will be available in the next release.
